### ISSUE TITLE
Azure AD----The redirect URI XXX specified in the request does not match the redirect URIs

### ISSUE THREAD

**Issue by Jinxin231** [jkroepke/openvpn-auth-oauth2#103]
This is detailed error information：

Request Id: 309871e1-882b-4b51-a738-2e87d2215c03
Correlation Id: 4b558249-711b-45cd-ba30-09c5e9b5adb7
Timestamp: 2024-01-03T08:40:59Z
Message: AADSTS50011: The redirect URI 'http://<ip>:9000/oauth2/callback' specified in the request does not match the redirect URIs configured for the application '0bf12583-c907-48ad-a45f-182b3d44379e'. Make sure the redirect URI sent in the request matches one added to your application in the Azure portal. Navigate to https://aka.ms/redirectUriMismatchError to learn more about how to fix this.

![image](https://github.com/jkroepke/openvpn-auth-oauth2/assets/4413463/ed92b12f-0bbf-4536-98c9-7edfc55113fc)

this is redirect_uri:
https://login.microsoftonline.com/XXXXXX/oauth2/v2.0/authorize?client_id=<clientId>&code_challenge=FSE0ppw-i0Gw59jB4M3eN4n27GSFvf060t5hbbzmsog&code_challenge_method=S256&nonce=AMzA7-wvRNzOZ7hfkfbHXtNWzq0KAAF0hihZQP2vaxulWsvcax0P6KGZSPEKQsd4scbaLg&redirect_uri=http%3A%2F%2F<IP>%3A9000%2Foauth2%2Fcallback&response_type=code&scope=openid+profile+email+offline_access&state=AMzA7-wvRNzOZ7hfkfbHXtNWzq0KAAF0hihZQP2vaxulWsvcax0P6KGZSPEKQsd4scbaLg

and this is Azure  AD config

![image](https://github.com/jkroepke/openvpn-auth-oauth2/assets/4413463/b8b36c65-3714-4208-8d40-1c121273e8e1)

my [openvpn-auth-oauth2](https://github.com/jkroepke/openvpn-auth-oauth2) conf
```typescript
CONFIG_OPENVPN_ADDR=unix:///run/openvpn-server/server.sock
CONFIG_OPENVPN_PASSWORD=xxx
CONFIG_OAUTH2_ISSUER=https://login.microsoftonline.com/xxx/v2.0
#CONFIG_OAUTH2_ISSUER=https://login.chinacloudapi.cn/dfc040c2-172e-4b45-8702-2d500250efbf/v2.0
CONFIG_OAUTH2_CLIENT_ID= #CLIENT_ID
CONFIG_OAUTH2_CLIENT_SECRET=#CLIENT_SECRET
CONFIG_HTTP_LISTEN=:9000
# Define a random value with 16 or 24 characters
CONFIG_HTTP_SECRET=1jd93h5b6s82lf03jh5b2hf9
# Define the public http endpoint here.
CONFIG_HTTP_BASEURL=http://<ip>:9000

``` 
can you help me? @jkroepke

**Comment by jkroepke** [comment]
> CONFIG_HTTP_BASEURL=http://<ip>:9000

The URLs here start with http://, but at Entra ID, it starts with `https://`.

Entra ID supports only `https://`

**Comment by Jinxin231** [comment]
> > CONFIG_HTTP_BASEURL=http://:9000
> 
> The URLs here start with http://, but at Entra ID, it starts with `https://`.
> 
> Entra ID supports only `https://` which is means you have to configure HTTPS

This means that these two parameters also need to be configured. Is my understanding correct?

#CONFIG_HTTP_KEY= 
#CONFIG_HTTP_CERT=

**Comment by Jinxin231** [comment]
> Add `CONFIG_HTTP_TLS=true`
> 
> See also: https://github.com/jkroepke/openvpn-auth-oauth2/wiki/Configuration#https-listener

![image](https://github.com/jkroepke/openvpn-auth-oauth2/assets/4413463/932e7a25-bfb7-40a9-9b6a-31ee3b43aa6d)

Wow, it can work now. Thank you very much!
