### ISSUE TITLE
Authentication failed after 1.13.0 with CONFIG_OAUTH2_VALIDATE_IPADDR=1 

### ISSUE THREAD

**Issue by hightrek** [jkroepke/openvpn-auth-oauth2#121]
### Current Behavior

When I have upgraded on version 1.13 or after, validation of IP adress doesn't work, we have this message:
level=WARN msg="missing claim: ipaddr"
If I rollback to 1.12.2, it's working.
On Azure, ipaddr claim has been setted

### Steps To Reproduce

```Markdown
1- On Debian package 1.13
2- With this config:
CONFIG_OPENVPN_ADDR=unix:///dev/openvpn
CONFIG_OAUTH2_ISSUER=https://login.microsoftonline.com/xxxxx/v2.0
CONFIG_OAUTH2_CLIENT_ID=xxxx
CONFIG_OAUTH2_CLIENT_SECRET=xxxx
CONFIG_HTTP_LISTEN=:443
CONFIG_HTTP_SECRET=xxxx
CONFIG_HTTP_BASEURL=https://xxxxx
CONFIG_HTTP_TLS=1
CONFIG_HTTP_CERT=xxxx
CONFIG_HTTP_KEY=xxxx
CONFIG_LOG_LEVEL=debug
CONFIG_HTTP_CALLBACK_TEMPLATE_PATH=https://xxx
CONFIG_HTTP_ENABLE__PROXY__HEADERS=1
CONFIG_OAUTH2_VALIDATE_IPADDR=1
```

### Environment

- openvpn-auth-oauth2 Version: 1.13
- OpenVPN Server Version: 2.6.3-1+deb12u2
- Server OS: Debian 12
- OpenVPN Client (flavor, OS): Windows 10, Client GUI 11.45.0.0 (Openvpn 2.6.7)

**Comment by jkroepke** [comment]
Thanks, for reporting. I figure out the issue any apply a fix.
