### ISSUE TITLE
Missing common_name Username

### ISSUE THREAD

**Issue by gruaig** [jkroepke/openvpn-auth-oauth2#132]
### Current Behavior

I have tried on a few clients and it doesn't seem to pick it up

time=2024-01-25T10:37:05.540Z level=INFO msg="accept OpenVPN client cid 26, kid 1" cid=26 kid=1 common_name="" idtoken.subject=ZTDL76jW67ch6sbug7r5FaP427EYygr4CjH3xqZPnmE47idtoken.preferred_username=example@email.comuser.subject=ZTDL7426jW67ch6sbug7r5FaPYygr4CjH3xqZPnmE48 user.preferred_username=example@email.com

time=2024-01-25T10:37:05.683Z level=INFO msg="client established" cid=26 common_name="" reason=ESTABLISHED username=""

### Expected Behavior

common_name="" reason=ESTABLISHED username="" both are blank on default setup for Viscosity and OpenVPN connect.  idtoken.preferred_username is populated 

### Steps To Reproduce

```Markdown
Ubuntu 23.04
OpenVPN 2.6.8 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] [DCO]
library versions: OpenSSL 3.0.2 15 Mar 2022, LZO 2.10
```

### Environment

- openvpn-auth-oauth2 Version: 1.13.5
- OpenVPN Server Version: 2.6.8
- Server OS: 23.04
- OpenVPN Client (flavor, OS): Tunnelblick beta , OpenVPN connect latest

### Anything else?

Nothing else to add.

**Comment by jkroepke** [comment]
Are you using client certificates? Or username/passwort auth?

**Comment by gruaig** [comment]
./client.crt:        Issuer: CN=test
./client.crt:        Subject: CN=test

**Comment by jkroepke** [comment]
Please post your OpenVPN config

**Comment by jkroepke** [comment]
This is the same issue as #163
