### ISSUE TITLE
"This site can’t provide a secure connection"   [ ERR_SSL_PROTOCOL_ERROR ]

### ISSUE THREAD

**Issue by ps92121** [jkroepke/openvpn-auth-oauth2#138]
### Current Behavior

It seems that I cannot get the certificates to bind to the native HTTPS listener within openvpn-auth-oauth2.  I've tried my own wildcard cert [from trusted authority] as well as generating a self-signed key/crt from the example provided.  I've turned the logging up to DEBUG level and do not see anything useful in there.

snippet of self-signed config below:

CONFIG_HTTP_BASEURL=https://ovpn1.mycompany.com:9000
CONGIG_HTTP_TLS=true
CONFIG_HTTP_KEY=/etc/sysconfig/server2.key
CONFIG_HTTP_CERT=/etc/sysconfig/server2.crt
CONFIG_LOG_LEVEL=DEBUG

I guess my question is where can I look to troubleshoot the native HTTPS listener and the loading of the crt and key into it?  

[If I change it to http:9000 the page will load properly, but unfortunately AAD will not accept http URLs for redirect.]

### Environment

- openvpn-auth-oauth2 Version: 1.13.5
- OpenVPN Server Version:    2.6.8 
- Server OS:  jammy
- OpenVPN Client (flavor, OS):  [tried both] on windows

### Anything else?

![image](https://github.com/jkroepke/openvpn-auth-oauth2/assets/31040342/8573c146-c973-43b2-9f75-27f739c6b530)

**Comment by jkroepke** [comment]
There are no logs on server side?

I fully depends agaist golang standard https listener with standard ciphersuite.

Are you using RSA key or EC keys for your SSL cert?

**Comment by ps92121** [comment]
yep you were right - the 'typo' was the issue,  once i fixed that - all i had to do was grant read permission to my key  [once i actually turned on TLS, there was a lot of useful information]

thanks for making this amazing 'plug-in'!!!!!
