### ISSUE TITLE
20s delay for autorization after process restart

### ISSUE THREAD

**Issue by andreas-p** [jkroepke/openvpn-auth-oauth2#144]
### Current Behavior

When restarting the openvpn-auth-oauth2 service, the next authorization will take a 20s nap:
```
time=2024-02-07T13:19:27.701+01:00 level=INFO msg="initialize authorization via oauth2" cid=4 kid=1
time=2024-02-07T13:19:47.884+01:00 level=INFO msg="successful authorization via oauth2" cid=4 kid=1
```
The client side browser will get a timeout (504 from the reverse proxy in front of openvpn-auth-oauth2), while accessing oauth2/callback. Still, after 20+ seconds, the connection is established successfully.

With log.level=DEBUG, nothing is logged in between.

After the first delayed auth, all others will succeed within fractions of a second as expected.

**Comment by jkroepke** [comment]
Do you have ip6 enabled on the server?

**Comment by andreas-p** [comment]
ipv6 is not disabled -> yes ;-)

**Comment by jkroepke** [comment]
Do you have experience in tcpdump?

A tcpdump could identify some system level behaviors which hard to identify from remote. Maybe a service endpoint not rechable but due automatic retries in go internals it within 20 seconds. 

The binary is not linked against libc and may behavior differently

**Comment by andreas-p** [comment]
Tcpdump with all known traffic filtered out gives zero packets during that 20s pause.
Apparently, the outh2 manager will pause after the userinfo endpoint was called.

**Comment by jkroepke** [comment]
Could you please enable the debug listener via `--debug.pprof`?

Then, if `initialize authorization via oauth2` comes up, please open the url `http://localhost:9001/debug/pprof/goroutine?debug=2` and save the output to a file. Please do this 3-4 times within the 20 seconds. It should give hints where the code is hanging.

**Comment by jkroepke** [comment]
In can see this one:

```
goroutine 45 [select]:
net/http.(*http2ClientConn).RoundTrip(0xc00035c000, 0xc000158d00)
	/opt/hostedtoolcache/go/1.21.5/x64/src/net/http/h2_bundle.go:8381 +0x44f
net/http.(*http2Transport).RoundTripOpt(0xc00012ef30, 0xc000158d00, {0x60?})
	/opt/hostedtoolcache/go/1.21.5/x64/src/net/http/h2_bundle.go:7649 +0x1b1
net/http.(*http2Transport).RoundTrip(0xd37160?, 0xc000360200?)
	/opt/hostedtoolcache/go/1.21.5/x64/src/net/http/h2_bundle.go:7598 +0x15
net/http.(*Transport).roundTrip(0xd37160, 0xc000158c00)
	/opt/hostedtoolcache/go/1.21.5/x64/src/net/http/transport.go:602 +0x78b
net/http.(*Transport).RoundTrip(0x0?, 0xc0000d2960?)
	/opt/hostedtoolcache/go/1.21.5/x64/src/net/http/roundtrip.go:17 +0x13
github.com/jkroepke/openvpn-auth-oauth2/internal/utils.(*UserAgentTransport).RoundTrip(0xc0001e3370, 0xc000158c00)
	/home/runner/work/openvpn-auth-oauth2/openvpn-auth-oauth2/internal/utils/http.go:20 +0xf7
net/http.send(0xc000158b00, {0xa22760, 0xc0001e3370}, {0x1?, 0x48e314?, 0xd3e1a0?})
	/opt/hostedtoolcache/go/1.21.5/x64/src/net/http/client.go:260 +0x606
net/http.(*Client).send(0xc0001a3950, 0xc000158b00, {0x3f?, 0x0?, 0xd3e1a0?})
	/opt/hostedtoolcache/go/1.21.5/x64/src/net/http/client.go:181 +0x98
net/http.(*Client).do(0xc0001a3950, 0xc000158b00)
	/opt/hostedtoolcache/go/1.21.5/x64/src/net/http/client.go:724 +0x912
net/http.(*Client).Do(...)
	/opt/hostedtoolcache/go/1.21.5/x64/src/net/http/client.go:590
golang.org/x/oauth2/internal.doTokenRoundTrip({0xa25aa0, 0xc0000d2900}, 0xc000158a00)
	/home/runner/go/pkg/mod/golang.org/x/oauth2@v0.16.0/internal/token.go:256 +0x112
golang.org/x/oauth2/internal.RetrieveToken({0xa25aa0, 0xc0000d2900}, {0xc000156600, 0x40}, {0xc000156780, 0x40}, {0xc0002c8000, 0x2e}, 0x957f2f?, 0x0, ...)
	/home/runner/go/pkg/mod/golang.org/x/oauth2@v0.16.0/internal/token.go:226 +0x112
golang.org/x/oauth2.retrieveToken({0xa25aa0, 0xc0000d2900}, 0xc00012ed80, 0xc?)
	/home/runner/go/pkg/mod/golang.org/x/oauth2@v0.16.0/token.go:167 +0x85
golang.org/x/oauth2.(*Config).Exchange(0xc00012ed80, {0xa25aa0, 0xc0000d2900}, {0xc000336775, 0x80}, {0xc0000c6260, 0x1, 0x0?})
	/home/runner/go/pkg/mod/golang.org/x/oauth2@v0.16.0/oauth2.go:234 +0x26f
github.com/zitadel/oidc/v3/pkg/client/rp.CodeExchange[...]({0xa25aa0, 0xc0000d2360?}, {0xc000336775?, 0x80}, {0xa28c40, 0xc0001d6b40}, {0xc000042450, 0x1, 0x1})
	/home/runner/go/pkg/mod/github.com/zitadel/oidc/v3@v3.10.2/pkg/client/rp/relying_party.go:434 +0x254
github.com/zitadel/oidc/v3/pkg/client/rp.CodeExchangeHandler[...].func1(0xc000158600)
	/home/runner/go/pkg/mod/github.com/zitadel/oidc/v3@v3.10.2/pkg/client/rp/relying_party.go:503 +0x6f7
net/http.HandlerFunc.ServeHTTP(0xa216f0?, {0xa24fc0?, 0xc000304000?}, 0xc0001d6b40?)
	/opt/hostedtoolcache/go/1.21.5/x64/src/net/http/server.go:2136 +0x29
github.com/jkroepke/openvpn-auth-oauth2/internal/oauth2.(*Provider).Handler.(*Provider).oauth2Callback.func3({0xa24fc0, 0xc000304000}, 0xc000158000)
	/home/runner/work/openvpn-auth-oauth2/openvpn-auth-oauth2/internal/oauth2/handler.go:210 +0x5c6
net/http.HandlerFunc.ServeHTTP(0x4459c0?, {0xa24fc0?, 0xc000304000?}, 0x6e8c3a?)
	/opt/hostedtoolcache/go/1.21.5/x64/src/net/http/server.go:2136 +0x29
net/http.(*ServeMux).ServeHTTP(0xd6d8e0?, {0xa24fc0, 0xc000304000}, 0xc000158000)
	/opt/hostedtoolcache/go/1.21.5/x64/src/net/http/server.go:2514 +0x142
net/http.serverHandler.ServeHTTP({0xc0002c41e0?}, {0xa24fc0?, 0xc000304000?}, 0x6?)
	/opt/hostedtoolcache/go/1.21.5/x64/src/net/http/server.go:2938 +0x8e
net/http.(*conn).serve(0xc00009e480, {0xa25aa0, 0xc0000d2480})
	/opt/hostedtoolcache/go/1.21.5/x64/src/net/http/server.go:2009 +0x5f4
created by net/http.(*Server).Serve in goroutine 33
	/opt/hostedtoolcache/go/1.21.5/x64/src/net/http/server.go:3086 +0x5cb
```

It seems like `openvpn-auth-oauth2` hangs at CodeExchangeHandler which current do a HTTP request against the token endpoint.

Sometimes, it could be an unidentified http2 issue. As I know, you could test the environment variable `GODEBUG=h2client=0` which should disable http2 and use http1.1 for connection.

**Comment by jkroepke** [comment]
if you run `curl -XPOST https://idp/index.php/apps/oidc/token`, without adding any creds, does it work without any issues?

**Comment by andreas-p** [comment]
I get an immediate 400 `{"error":"invalid_grant","error_description":"Invalid grant_type provided. Must be authorization_code or refresh_token."}` as expected.

**Comment by jkroepke** [comment]
> I get an immediate 400 `{"error":"invalid_grant","error_description":"Invalid grant_type provided. Must be authorization_code or refresh_token."}` as expected.
> 
> 

Still a different from the 401 answer.

Which IDP your are using?

**Comment by andreas-p** [comment]
It's Nextcloud. Since I curl-posted neither auth-code nor rfsh-token, 400 appears precise to me.
Nextcloud will log "Login failed: <oidc-client-id>". If this would happen all the time, I'd point towards Nextcloud, but it only happens for the first auth attempt after openvpn-auth-oauth2 was restarted. All following auths are performed fast and flawlessly.

**Comment by jkroepke** [comment]
Could you please re-do this

> Could you please enable the debug listener via `--debug.pprof`?
> 
> Then, if `initialize authorization via oauth2` comes up, please open the url `http://localhost:9001/debug/pprof/goroutine?debug=2` and save the output to a file. Please do this 3-4 times within the 20 seconds. It should give hints where the code is hanging.

with `GODEBUG=http2client=0` in hope, that the http function for http11 is more readable? http2 is to complex to debug

**Comment by andreas-p** [comment]
In the meantime, I had the machine slightly reconfigured, config file cleanup, other VLAN. The error didn't occur any more... I moved the machine back to the initial VLAN, no 20s delay. Moving back to the final VLAN again (only VLAN/IPaddr changed), and there it was again, the 20s delay after service restart....

So here's the logs: log.0 before connect, log.x after success.

[pprof2.tgz](https://github.com/jkroepke/openvpn-auth-oauth2/files/14223226/pprof2.tgz)

**Comment by jkroepke** [comment]
Based on the dump, I still can see that go is waiting for an action. Until a timeout of 20 seconds hits.

https://github.com/jkroepke/openvpn-auth-oauth2/blob/acee037fb615611b345d6a3205a8c963f424a73c/internal/oauth2/provider.go#L152

The 20 seconds are configured in openvpn-auth-oauth2 to prevent any deadlocks.

Anyways I have no idea how I could debug this from remote. Its somewhere deeper in the go language or in the network topology, if it could be fixed an VLAN change.

**Comment by andreas-p** [comment]
Since the machine is virtualized, it doesn't know about the VLAN change, just the IP addr change... I guess it was just the reboot that re-enabled the problem. Maybe some RNG stuff?

**Comment by jkroepke** [comment]
Here is my current guess for the issue:

openvpn-auth-oauth2 uses and library for oauth2 which uses the go standard lib.

While OIDC exists as spec, many providers my not implement all variants. 

Since we have the token endpoint in scope, a token can be received in 2 different "auth styles", if client ID and client secret is in use: `client_secret_basic` and `client_secret_post`

Ref: https://cloudentity.com/developers/basics/oauth-client-authentication/client-secret-authentication/

A full generic OAUTH2 doesn't know, whats supported and there is no spec to advertise the auth method. Based that, clients may require multiple try to detect what is working.

https://github.com/golang/oauth2/blob/ebe81ad83719fe3426335b22e40a1e3a76fa45c0/internal/token.go#L212-L253

If nothing is known, the client tries to use `client_secret_basic` first where the credentials are put in the Authorization header. It seems like Nextcloud may have an issue here or the Authorization header my not pass through nginx.

Then `client_secret_post` is used, where the credentials are put inside a POST body. Since this worked, the oauth2 client cache the information which method has been used unless the service gets an restart.

Thats the reason why 2 requests are visible for first time.

To mitigate the issue from  `openvpn-auth-oauth2` side, I have to make the auth style parameter configurable, but the underlaying library currently does not allow this.

**Comment by jkroepke** [comment]
@andreas-p Are you able to the the binary here, if the behavior still present?

https://github.com/jkroepke/openvpn-auth-oauth2/actions/runs/8024800554/artifacts/1270912217

It should work, w/o changes any options.
