### ISSUE TITLE
openvpn.passwordfile

### ISSUE THREAD

**Issue by andreas-p** [jkroepke/openvpn-auth-oauth2#145]
### Problem Statement

Cleartext passwords should be in as few places as possible, so I propose to read the openvpn management password from a file. This would re-use the password.txt file that openvpn already requires, via a configuration option `openvpn.passwordfile`.

**Comment by jkroepke** [comment]
there is a lack in documentation

The following paramter support files

* http.secret
* openvpn.password
* oauth2.client.secret
* oauth2.refresh.secret

---
For example

* `openvpn.password=file://<file-path>`

Credentials can be encrypted via systemd, see: https://systemd.io/CREDENTIALS/

**Comment by andreas-p** [comment]
Yes, that file:// works for me, so it's just a documentation issue.
FWIW, I prefer configuration using the config file. A sample config file would be nice, because it isn't clear how to write the tags when dots and hyphens are involved.

**Comment by jkroepke** [comment]
The config file is YAML based. hyphens are not touch and each dot is a new key.

The option `oauth2.authorize-params` should be

```yaml
oauth2:
  authorize-params:
```
