### ISSUE TITLE
Openvpn management interface passthrough (OpnSense compatibility)

### ISSUE THREAD

**Issue by andreas-p** [jkroepke/openvpn-auth-oauth2#146]
### Problem Statement

openvpn will serve only one manager connection, additional connections don't receive status or take commands.

### Proposed Solution

Unless openvpn-auth-oauth2 is going to implement a state-of-the-art REST and/or websocket API to control the openvpn server :-), I propose that the program should serve an additional port, passing through all openvpn status messages, and commands issued on that port, to enable external openvpn managers to work again.
That Man-In-The-Middle would probably enable all existing solutions to work (I guess currently OpenVPN AS blocks the management port itself?).

**Comment by jkroepke** [comment]
Not sure about this. A dedicated program which acts as de/multiplexer for the management interface would be better here.

I would like to avoid much fancy stuff to avoid additional complexity.

**Comment by jkroepke** [comment]
What the job of the other management client in your case?

**Comment by andreas-p** [comment]
There are like a myriad management interface clients out there to visualize the current connection status and kill single connections (I guess OpenVPN AS does just that).

**Comment by jkroepke** [comment]
Did you mean that you are using OpenVPN AS together with openvpn-auth-oauth2?

That what I find, if I google myriad and openvpn.

**Comment by andreas-p** [comment]
No, searching for "openvpn server admin GUI".
I'm using OpnSense for many years now, which, no surprise, uses the management interface.

**Comment by ncioj10** [comment]
@andreas-p Did you manage to run this in tandem with an OpnSense managed OpenVPN server or what is your current approach? 
Currently, my plan is to setup an Azure AD/Entra <-> OpnSense + OpenVPN based OpenVPN login, but I have little experience in installing additional modules with OpnSense.

**Comment by andreas-p** [comment]
@ncioj10 I'm running the oauth2-enabled instance on Debian, no GUI management.

**Comment by jkroepke** [comment]
@andreas-p Would be a readonly passthrough sufficient?

**Comment by andreas-p** [comment]
Managers offer to kill single connections, so no.

**Comment by jkroepke** [comment]
@andreas-p could you please provide some feedback about the passthrough feature?

Its available in the current RC

https://github.com/jkroepke/openvpn-auth-oauth2/releases/tag/v1.16.0-rc.3

**Comment by andreas-p** [comment]
I won't have time to check admin GUIs in the next days, but checked passthrough with telnet:
`status` and `kill`worked fine as expected, but I guess most managers would like to see all openvpn messages like `>CLIENT` as well.

**Comment by andreas-p** [comment]
Ok did check with a client, https://github.com/furlongm/openvpn-monitor:
- Monitor expects lines to be terminated `\r\n`, oaa terminates with `\n` only.
- oaa passes `quit` as well, which makes OpenVpn disconnect oaa, shutting down oaa.

**Comment by jkroepke** [comment]
> * oaa passes `quit` as well, which makes OpenVpn disconnect oaa, shutting down oaa.

Ah, I take only care of `exit`

**Comment by jkroepke** [comment]
Thanks for the review
