### ISSUE TITLE
Layout changed

### ISSUE THREAD

**Issue by Pionerd** [jkroepke/openvpn-auth-oauth2#162]
### Current Behavior

Current layout is less pretty than it used to be in previous releases

![Screenshot 2024-02-12 at 13 22 02](https://github.com/jkroepke/openvpn-auth-oauth2/assets/110168856/f1abfe33-8a67-4ca9-b093-b162208613b0)

### Expected Behavior

Please revert to the old lay out, options to make it configurable (css/own logo) would be awesome but not required.

### Environment

- openvpn-auth-oauth2 Version:
- OpenVPN Server Version:
- Server OS:
- OpenVPN Client (flavor, OS):
- OIDC Provider:

**Comment by jkroepke** [comment]
I guess regression introduced in https://github.com/jkroepke/openvpn-auth-oauth2/pull/157
