### ISSUE TITLE
[Google] Refresh token

### ISSUE THREAD

**Issue by Pionerd** [jkroepke/openvpn-auth-oauth2#166]
### Problem Statement

Logs for google say: `Feb 12 15:09:32 shared-hub-vpn-gateway openvpn-auth-oauth2[78178]: time=2024-02-12T15:09:32.333Z level=WARN msg="oauth2.refresh is enabled, but provider does not return refresh token"`

If I search online, refresh tokens seem to be supported. Also your Google codes seems to mention getting refresh tokens. Is it supported? 

### Environment

- openvpn-auth-oauth2 Version:
- OpenVPN Server Version:
- Server OS:
- OpenVPN Client (flavor, OS):

**Comment by jkroepke** [comment]
I have no idea. Reading docs (https://developers.google.com/identity/protocols/oauth2/web-server#exchange-authorization-code), set `access_type=offline` is sufficient which I do

https://github.com/jkroepke/openvpn-auth-oauth2/blob/5840fd9628a3e351929ebd85a4381142556d18c8/internal/oauth2/providers/google/config.go#L18

But it has no effect or something in that code wont work and the parameter is not set.

**Comment by Pionerd** [comment]
I found and tested this: https://stackoverflow.com/questions/10827920/not-receiving-google-oauth-refresh-token

I can confirm that this time the warning is not shown for my user. Maybe adding the `prompt=consent` helps?

**Comment by jkroepke** [comment]
You could test this with 

> CONFIG_OAUTH2_AUTHORIZE__PARAMS="prompt=consent"
