### ISSUE TITLE
Status of Keycloak Support?

### ISSUE THREAD

**Issue by alee-ntap** [jkroepke/openvpn-auth-oauth2#170]
### Problem Statement

The `README.md` of the project mentioned `keycloak` as a supported Identity Provider (IdP). However, the `Providers.md` document has no mention of keycloak. This raises doubts about the current status of `keycloak` integration with `openvpn-auth-oauth2`.

I would like to seek clarification on the following points:

1. Is keycloak officially supported as an IdP?
2. If so, what is the recommended approach for configuring keycloak?
3. If keycloak support is not available or recommended, could you suggest any alternative self-hosted IdP, such as Hydra, that can be used with `openvpn-auth-oauth2`?

These clarifications will help me make an informed decision regarding the choice of IdP for `openvpn-auth-oauth2`. Thank you for your assistance.

### Environment

- openvpn-auth-oauth2 Version: latest
- OpenVPN Server Version: 2.6.8
- Server OS: FreeBSD
- OpenVPN Client (flavor, OS): Tunnelblick 4.0.0beta13 / MacOS

**Comment by jkroepke** [comment]
> * Is keycloak officially supported as an IdP?

openvpn-auth-oauth2 officially supported any OIDC compliant IDP. As I know, Keycloak is OIDC compliant and should work.

However, I do not have much experience in Keycloak and I currently depend on the community to provide some documentation.

> If so, what is the recommended approach for configuring keycloak?

There isn't a recommended approach yet. If you feel confident, you can provide a recommended approach

You can follow the guide from oauth2-proxy. I recently copy the documentation for Google Workspace which got reviewed by an community member.

https://oauth2-proxy.github.io/oauth2-proxy/configuration/providers/keycloak_oidc

> If keycloak support is not available or recommended

I can't give you a good recommendation here. As I know, Keycloak has the large user-based.

An other community member contribute a documentation for Zitadel, but I never heard Zitadel before.
