### ISSUE TITLE
IOS OpenVPN Connect will disconnect  after lock screen for about 20 seconds and can not auto re-connect after unlock

### ISSUE THREAD

**Issue by ihipop** [jkroepke/openvpn-auth-oauth2#184]
### Current Behavior

when I lock the screen， after about 20s  after the screen turns to black,  the server will get a message that the client has disconnected
when I unlock it, the IOS OpenVPN Connect will pop up a message and says that the connection has been disconnected
I have to open the app again and wait for the browser to open and then auto-close
**this could not be done in the background with auto**

this option still helps nothing

![image](https://github.com/jkroepke/openvpn-auth-oauth2/assets/423077/e12603f4-9e27-4c86-8861-44f98402497b)

`oauth2.refresh.enabled=true` enabled too

![image](https://github.com/jkroepke/openvpn-auth-oauth2/assets/423077/1fecbc11-88c9-4ece-97bf-f954258d4326)

**If I disable `openvpn-auth-oauth2`, the auto-reconnect will be done in  the background without any manual access**

### Expected Behavior
```
-
```
### Steps To Reproduce

```Markdown
-
```

### Environment

- openvpn-auth-oauth2 Version: `master`
- OpenVPN Server Version: `OpenVPN 2.6.8 [git:makepkg/3b0d9489cc423da3+] x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] [DCO] built on Nov 17 2023`
- Server OS: `Manjaro Linux 23.1.3`
- OpenVPN Client (flavor, OS):  `OpenVPN Connect 3.4.1 (5463)/ IOS 15.8.1`
- OIDC Provider: `STD oauth2 provider`

### openvpn-auth-oauth2 logs

```
time=2024-02-19T09:17:01.092+08:00 level=INFO msg="new client connection" cid=67 kid=1 common_name=test@example.com reason=CONNECT username=""
time=2024-02-19T09:17:01.092+08:00 level=INFO msg="start pending auth" cid=67 kid=1 common_name=test@example.com reason=CONNECT username=""
time=2024-02-19T09:17:02.903+08:00 level=INFO msg="client disconnected" cid=66 common_name=test@example.com reason=DISCONNECT username=""
time=2024-02-19T09:17:22.231+08:00 level=INFO msg="initialize authorization via oauth2" cid=67 kid=1 common_name=test@example.com
time=2024-02-19T09:17:22.814+08:00 level=INFO msg="successful authorization via oauth2" cid=67 kid=1 common_name=test@example.com idtoken.subject=on_a0cb95cc0a79d1d72d11050d855ac1c5 idtoken.preferred_username="" user.subject=on_a0cb95cc0a79d1d72d11050d855ac1c5 user.preferred_username=""
time=2024-02-19T09:17:22.814+08:00 level=INFO msg="accept OpenVPN client cid 67, kid 1" cid=67 kid=1 common_name=test@example.com idtoken.subject=on_a0cb95cc0a79d1d72d11050d855ac1c5 idtoken.preferred_username="" user.subject=on_a0cb95cc0a79d1d72d11050d855ac1c5 user.preferred_username=""
time=2024-02-19T09:17:26.120+08:00 level=INFO msg="client established" cid=67 common_name=test@example.com reason=ESTABLISHED username=""
time=2024-02-19T09:17:59.607+08:00 level=INFO msg="client disconnected" cid=67 common_name=test@example.com reason=DISCONNECT username=""
```

### openvpn server logs

```
2024-02-19 09:17:01 172.18.1.243:59878 peer info: IV_VER=3.8.3connect1
2024-02-19 09:17:01 172.18.1.243:59878 peer info: IV_PLAT=ios
2024-02-19 09:17:01 172.18.1.243:59878 peer info: IV_NCP=2
2024-02-19 09:17:01 172.18.1.243:59878 peer info: IV_TCPNL=1
2024-02-19 09:17:01 172.18.1.243:59878 peer info: IV_PROTO=990
2024-02-19 09:17:01 172.18.1.243:59878 peer info: IV_MTU=1600
2024-02-19 09:17:01 172.18.1.243:59878 peer info: IV_CIPHERS=AES-128-CBC:AES-192-CBC:AES-256-CBC:AES-128-GCM:AES-192-GCM:AES-256-GCM:CHACHA20-POLY1305
2024-02-19 09:17:01 172.18.1.243:59878 peer info: IV_AUTO_SESS=1
2024-02-19 09:17:01 172.18.1.243:59878 peer info: IV_GUI_VER=net.openvpn.connect.ios_3.4.1-5463
2024-02-19 09:17:01 172.18.1.243:59878 peer info: IV_SSO=webauth,openurl,crtext
2024-02-19 09:17:01 172.18.1.243:59878 peer info: IV_BS64DL=1
2024-02-19 09:17:01 172.18.1.243:59878 [test@example.com] Peer Connection Initiated with [AF_INET]172.18.1.243:59878
2024-02-19 09:17:26 test@example.com/172.18.1.243:59878 MULTI_sva: pool returned IPv4=10.172.18.2, IPv6=(Not enabled)
2024-02-19 09:17:54 test@example.com/172.18.1.243:59878 CC-EEN exit message received by peer
2024-02-19 09:17:54 read UDPv4 [ECONNREFUSED]: Connection refused (fd=5,code=111)
```

**Comment by ihipop** [comment]
And I've tried the official https://openvpn.net/cloud-vpn/  it will disconnect after lock screen too

but **it will auto-reconnect in the background without any manual operation** when I turn the screen on. which is acceptable

**Comment by ihipop** [comment]
I see, it's about the auth-token issue
 add these lines to the client configuration to fix the issue

``
setenv USERNAME "OAUTH_SUBJECT"
``

**Comment by ihipop** [comment]
Related: https://github.com/OpenVPN/openvpn/issues/296

**Comment by jkroepke** [comment]
If you are using the official OpenVPN cloud, then OpenVPN will use username/password authentication. While `openvpn-auth-oauth2` fully depends on WEBAUTH. WEBAUTH the required here to ensure that admins can additional layers of authentication, e.g. MFA.

The openvpn.refresh.enabled=true works only, if the client get not disconnected. There is currently no chance, to detect an user between 2 connections.

A possible workaround cloud be, that you are define some dummy username/password on the OpenVPN client profile. `openvpn-auth-oauth2` will not take care about them, and will open the browser anyways.

Then, configure `auth-token-gen` on OpenVPN server. Please note that there will be no re-authentication on the SSO provider, because OpenVPN will handle the REAUTH alone.

**Comment by ihipop** [comment]
@jkroepke 

the official OpenVPN cloud doesn't require any password authentication, they just use webauth too
you can try it for free https://openvpn.net/cloud-vpn/
and I can confirm that there is not any PASSWORD in their config file

**Comment by ihipop** [comment]
> configure `auth-token-gen` on OpenVPN server.

I've already tried, it just failed directly .  when ios wakeup

the  server log just said : `TLS: Username/auth-token authentication failed for username ''`
the client side log: AUTH_FAILED

**Comment by jkroepke** [comment]
Then we may have to expect that OpenVPN cloud running a non public OpenVPN server version with additional patches.

As you already mention, auth-token requires an username to be set first. 

* https://github.com/OpenVPN/openvpn/issues/296

And there is currently no implementation to set/override the username from server-side:

* https://github.com/OpenVPN/openvpn/issues/299

You can upvote them, maybe it helps.

If `auth-token-gen`  is configured, remove `auth-user-pass-optional` to ensure that each client has defined a username via `auth-user-pass`.

**Comment by ihipop** [comment]
remove `auth-user-pass-optional` will make WEBAUTH hangs and then leads to fail
https://forums.openvpn.net/viewtopic.php?t=31835
this bug was reported in 2021 

I've dive into the OPENVPN code base and find out that  

https://github.com/OpenVPN/openvpn/blob/54475711eb119f6fbb263880fca08d4b10df752a/src/openvpn/ssl_verify.c#L1655

even if there is any error when verifying the auth token, there should any error message be reported

https://github.com/OpenVPN/openvpn/blob/6640a10bf6d84eeecc874b97e7c766bf84eef23f/src/openvpn/auth_token.c#L304-L400

but actually not

and I can see in the code **that empty username is also ok when verifying the auth token**

https://github.com/OpenVPN/openvpn/blob/6640a10bf6d84eeecc874b97e7c766bf84eef23f/src/openvpn/auth_token.c#L339-L346


so this is wired !

**Comment by jkroepke** [comment]
> remove `auth-user-pass-optional` will make WEBAUTH hang and then lead to fail
> [forums.openvpn.net/viewtopic.php?t=31835](https://forums.openvpn.net/viewtopic.php?t=31835)
> this bug was reported in 2021

But the bug was fixed?

**Comment by ihipop** [comment]
after dived into the OPENVPN codebase 
I makde a guess about how they've made this work
I will test it and if it works, I will open a PR against DOC/CODE to "fix/archive" this mode

**Comment by jkroepke** [comment]
@ihipop are you using client certificates for OpenVPN Cloud/openvpn-auth-oauth2?

**Comment by jkroepke** [comment]
https://www.mail-archive.com/openvpn-devel@lists.sourceforge.net/msg18819.html

Seems like 

`auth-token-gen 3600 external-auth`

enables this behaivor

**Comment by ihipop** [comment]
> https://www.mail-archive.com/openvpn-devel@lists.sourceforge.net/msg18819.html
> 
> Seems like
> 
> `auth-token-gen 3600 external-auth`
> 
> enables this behaivor

yes, it is, and  external-auth still needs some work on the openvpn-auth-oauth2 side , which is I'm working on

**Comment by ihipop** [comment]
> https://www.mail-archive.com/openvpn-devel@lists.sourceforge.net/msg18819.html
> 
> Seems like
> 
> `auth-token-gen 3600 external-auth`
> 
> enables this behaivor

The actual situation is that even I enable external auth，the OpenVPN server still returns a AUTH failure to the client
this is wired, I think it might be a bug
And we can't control how to gen session-id or validate it
so we must do it on the openvpn-auth-oauth2 side

I have roughly done and confirmed this works without enabling `uth-token-gen`
I will submit a PR when the polish is done

**Comment by jkroepke** [comment]
> And we can't control how to gen session-id or validate it so we must do it on the openvpn-auth-oauth2 side

I would disagree here.

Reading https://openvpn.net/community-resources/reference-manual-for-openvpn-2-6/#server-options 



> When the external-auth keyword is present the normal authentication method will always be called even if auth-token succeeds. Normally other authentications method are skipped if auth-token verification succeeds or fails.
> 
> This option postpones this decision to the external authentication methods and checks the validity of the account and do other checks.
> 
> In this mode the environment will have a session_id variable that holds the session id from auth-gen-token. Also an environment variable session_state is present. This variable indicates whether the auth-token has succeeded or not. It can have the following values:
> 
> * Initial
> No token from client.
> * Authenticated
> Token is valid and not expired.
> * Expired
> Token is valid but has expired.
> * Invalid
> Token is invalid (failed HMAC or wrong length)
> * AuthenticatedEmptyUser / ExpiredEmptyUser
> The token is not valid with the username sent from the client but would be valid (or expired) if we assume an empty username was used instead. These two cases are a workaround for behaviour in OpenVPN 3. If this workaround is not needed these two cases should be handled in the same way as Invalid.


session_id and auth-token will be still validated by OpenVPN server, but the validation result will be stored into `session_state` environment variable. Then OpenVPN is calling openvpn-auth-oauth2.

There is also a special `AuthenticatedEmptyUser` state which works, if client has an empty username.

Instead generate an own auth-token, I would prefer that OpenVPN does this for me, and i would like to have an focus on session_state exclusively. 

What did you think? See #189

**Comment by ihipop** [comment]
just try it
when username is empty, enabled `auth-token-gen` even with `external-auth`, the server will give the client an "AUTH_FAIL" directly and does not talk to management interface

**Comment by jkroepke** [comment]
> the server will give the client an "AUTH_FAIL" directly and does not talk to management interface

I tested this locally with an OpenVPN 3 client and I did not had the behavior.

**Comment by ihipop** [comment]
> > the server will give the client an "AUTH_FAIL" directly and does not talk to management interface
> 
> I tested this locally with an OpenVPN 3 client and I did not had the behavior.

what's your openvpn server version?

**Comment by ihipop** [comment]
The error message will occur on the second auto-reconnect when wakeup from sleep
which is described on the first floor

**Comment by jkroepke** [comment]
> what's your openvpn server version?

2.6.9

> it's what auth-token used for (not for the first connection)

I read the log from 

https://github.com/jkroepke/openvpn-auth-oauth2/issues/184#issuecomment-1951724047

and it uses SessionID/Auth-token after wake-up to authenticate here.

**Comment by ihipop** [comment]
> > what's your openvpn server version?
> 
> 2.6.9
> 
> > it's what auth-token used for (not for the first connection)
> 
> I read the log from
> 
> [#184 (comment)](https://github.com/jkroepke/openvpn-auth-oauth2/issues/184#issuecomment-1951724047)
> 
> and it uses SessionID/Auth-token after wake-up to authenticate here.

Yes,this is a second re-connect  log to the OpenVPN cloud, they send a auth-token to the client after webauth is success
the second auto re-connect will use auth-token instead of webauth

on my self openvpn server if I enable auth-token-gen , it will fail when  auto re-connect  from wakeup

>  Instead generate an own auth-token, I would prefer that OpenVPN does this for me, and i would like to have an focus on session_state exclusively.

if this is working,there is no need for us to care about the session-state, openvpn server will auto-auth the auto re-connect 

but unfortunately, this doesn't work on my server auto re-connect  from wakeup，management interface got nothing,
only an errorlog like this

` TLS: Username/Password authentication succeeded for username '' `

external-auth or not changes nothing

**Comment by jkroepke** [comment]
> if this is working,there is no need for us to care about the session-state

While I was testing, OpenVPN also passes sessions_state with `Expired`. I thought, OpenVPN is calling external-auth, even token failure.

**Comment by ihipop** [comment]
> Please mention that restarting the OpenVPN server makes all tokens invalid.

Iknow about that ，and there is an option to make the auth-token persistent after OpenVPN restart

> While I was testing, OpenVPN also passes sessions_state with Expired. I thought, OpenVPN is calling external-auth, even token failure.

IMO, If the server itself can verify auth-token，I don't think it‘s a good idea to have external-auth to interpose

I will try again to test why auth-gen-token not working on my machine

**Comment by jkroepke** [comment]
> I don't think it‘s a good idea to have external-auth to interpose

I feel it is. `openvpn-auth-oauth2` has the capability to ask to OIDC provider, if the user is still enabled or expired. So it can performs additional checks without user-interaction.

**Comment by ihipop** [comment]
I will try again still this error

without external-auth

```
TLS: Username/Password authentication failed for username ''
```



with  external-auth


`>CLIENT:ENV,session_state=Initial`

this value always be `Initial` which expected to `AuthenticatedEmptyUser`  or other value instead

**Comment by jkroepke** [comment]
> setenv USERNAME "test@example.com"

thats an funny hack.

**Comment by ihipop** [comment]
> > setenv USERNAME "[test@example.com](mailto:test@example.com)"
> 
> thats an funny hack.

picked from OpenVPN cloud
you really should try it
it's free

**Comment by ihipop** [comment]
close since we've found a solution

**Comment by jkroepke** [comment]
@ihipop 

Sorry, for me isn't it clear now. I may need a summarize here.

Does the PR #189  work or not?

I guess 

> setenv USERNAME "test@example.com"

is mandatory then here. Is OpenVPN cloud also using test@example.com?

**Comment by ihipop** [comment]
I write some test to confirm that this is not mandatory
the server pushed auth-token-user works too
openvpn cloud write this directive with the common name

whether you set it or not，via set env or via auth-token-user，if you let
openvpn server to validate the auth-token it will always fail with empty
username（which is wired）

only when external-auth is enabled，and username hint is set（via set env or
pushed auth-token-user ），the management interface will receive correct
session state

I’ve not test #189， but I Think it should work

**Comment by jkroepke** [comment]
I installed OVPN on my iPhone and it works. But it seems like auth-tokens are not getting refreshed.

**Comment by ihipop** [comment]
I've made a roughly fork of #189,keep the main logic of the using
session-id,but make session-id option mandatory, it works fine,you can find
it in my fork repo branch

Why I'm doing this?
Because CID always changes between re-connect, it's only keep the same
during re-auth,which will obviously miss the token cache

And the session-id is keep the same between re-connect and re-auth,and it's
validation is fast than none interactive oauth refresh,this is the meaning
of the using of auth-token


I don't know what's your configuration, but my auth-token renew normally


I will introduce my configuration and explain why

1. I set the life-time of auth-token to 0
2. I set the reneg-sec interval to 120 for testing purpose
3. Also，external-auth is enabled
4. a fixed auth-token-secret is set to make the auth-token survive server
restart

this configuration makes the life-time of auth token is only relative with
reneg-sec

when it combinations with my fork of #189
if the clients keeps online ，the auth-token get re-newed every re-auth for
ever,only auth-token validation is used，which is very quick and efficient

when it comes to the re-connect:
- if the client reconect during 2*reneg-sec，the token keeps valid,all goes
the same
- if the client reconnect interval > 2*reneg-sec
the token will always Expired, but the session-id keeps the same,so none
interactive oauth refresh will working normally again session-id, this is
the side effects of using gen-auth-token of OpenVPN server,I will consider
a fork to write an auth-token push and validation impleation on management
interface side (which you don't agree,so in my fork only),to re-push/re-new
auth-token if none interactive oauth2 refresh is successful

**Comment by ihipop** [comment]
> I do it, too. If `oauth2.refresh.use-session-id` is set to `true`, then `session_id` will be used instead CID.

That's different, in your  #189, when session-state is valid you still initiate an none interactive oauth2 refresh, just as the code review I've commented

In my fork of force session-ID, if auth-token is valid I will skip the none interactive oath2 refresh

> > 1. I set the life-time of auth-token to 0
> 
> Thats the difference. I may raise an question on OpenVPN.

This is explained in the document, the lifetime of auth-token is the minimum between life-time or 2*reneg-sec

**Comment by jkroepke** [comment]
I'm going to re-open this, because of #193

**Comment by Jinxin231** [comment]
@ihipop 你好，可以参考下server和client的配置吗？
我现在的情况是同一份配置文件，在pc端可以登录成功，但是ios端一直是失败的

**Comment by ihipop** [comment]
> @ihipop 你好，可以参考下server和client的配置吗？ 我现在的情况是同一份配置文件，在pc端可以登录成功，但是ios端一直是失败的

你同一份配置 common name 应该是一样的 那么你要打开duplicated-cn

如果不是这个问题 你需要提供更多的日志。目前这个issue和你的问题应该无关。

**Comment by Jinxin231** [comment]
> > @ihipop 你好，可以参考下server和client的配置吗？ 我现在的情况是同一份配置文件，在pc端可以登录成功，但是ios端一直是失败的
> 
> 你同一份配置 common name 应该是一样的 那么你要打开duplicated-cn
> 
> 如果不是这个问题 你需要提供更多的日志。目前这个issue和你的问题应该无关。

是的，没有关系，我只是不知道怎么联系到你。

auth-auth2的日志，只能看到这些错误日志，和我操作登录的时间点并不对应

May 07 13:44:26 iZt4ni0kuiwfr63npcjj9bZ openvpn-auth-oauth2[31768]: time=2024-05-07T13:44:26.825+08:00 level=ERROR msg="http: TLS handshake error from 80.66.83.47:39284: tls: first record does not look like a TLS handshake"
May 07 13:44:30 iZt4ni0kuiwfr63npcjj9bZ openvpn-auth-oauth2[31768]: time=2024-05-07T13:44:30.493+08:00 level=ERROR msg="http: TLS handshake error from 80.66.83.47:43836: read tcp 10.118.1.1:9000->80.66.83.47:43836: i/o timeout"
May 07 13:44:31 iZt4ni0kuiwfr63npcjj9bZ openvpn-auth-oauth2[31768]: time=2024-05-07T13:44:31.142+08:00 level=ERROR msg="http: TLS handshake error from 80.66.83.47:35238: tls: first record does not look like a TLS handshake"

client 配置
‘client
dev tun
proto tcp
remote #.#.#.# 11945
resolv-retry 20
resolv-retry infinite
nobind
persist-key
persist-tun
key-direction 1
comp-lzo
verb 3
;cipher AES-256-GCM
<ca>
-----BEGIN CERTIFICATE-----
-----END CERTIFICATE-----
</ca>
<cert>
-----BEGIN CERTIFICATE-----
-----END CERTIFICATE-----
</cert>
<key>
-----BEGIN PRIVATE KEY-----
-----END PRIVATE KEY-----
</key>
<tls-auth>
# 2048 bit OpenVPN static key
-----END OpenVPN Static key V1-----
</tls-auth>
<auth-user-pass>
 test-username-123
 testpassword
</auth-user-pass>
’

server 配置
`port 11945
proto tcp
dev tun
ca /etc/openvpn/server/keys/ca.crt
cert /etc/openvpn/server/keys/server.crt
key /etc/openvpn/server/keys/server.key
tls-auth /etc/openvpn/server/keys/ta.key 0
dh /etc/openvpn/server/keys/dh.pem
#server 10.10.10.0 255.255.255.0
server 10.8.0.0 255.255.255.0

#push "route 10.0.0.0 255.0.0.0"
push "route 10.0.0.0 255.128.0.0"
#push "route 10.100.0.0 255.255.255.0"


ifconfig-pool-persist /var/log/openvpn/ipp.txt
keepalive 10 120
cipher AES-256-GCM
persist-key
persist-tun
comp-lzo
status /var/log/openvpn/openvpn-status.log
log /var/log/openvpn/openvpn.log
verb 3
duplicate-cn

script-security 3
#auth-user-pass-verify /etc/openvpn/server/psw/checkpsw.sh via-env
#username-as-common-name
verify-client-cert none

client-to-client
client-config-dir /etc/openvpn/server/ccd


;# /etc/openvpn/password.txt is a password file where the password must be on first line
management /run/openvpn-server/server.sock unix /etc/openvpn/server/password.txt
management-hold
management-client-auth`

**当前卡在浏览器输入完用户名密码之后，提示“Access denied”** 可以给一点建议吗？
