### ISSUE TITLE
A possible chan deadlock with `commandResponseCh`

### ISSUE THREAD

**Issue by ihipop** [jkroepke/openvpn-auth-oauth2#190]
### Current Behavior

![image](https://github.com/jkroepke/openvpn-auth-oauth2/assets/423077/98091614-cdbf-4d9f-b4c6-ddf4a41504e9)

sometimes， the client can not connect to the server， and the openvpn-auth-oauth2 receives nothing

If I restart openvpn-auth-oauth2  and it works again and about some random time-lapse, it hangs again

I did some research , _and some test code （so ，the code line of the stack  in the photo is not the same as with main branch）_, and then dumped the stack when it hangs

I found a chan write blocked about 63 minutes,which is almost the time of my investigate period when I found it hangs

### Expected Behavior

no hangs

### Steps To Reproduce

```Markdown
-
```

### Environment

- openvpn-auth-oauth2 Version: `master`
- OpenVPN Server Version: -
- Server OS: -
- OpenVPN Client (flavor, OS): -
- OIDC Provider: -

### openvpn-auth-oauth2 logs

```shell
HANGS, nothing
```

### openvpn server logs

```shell
-
```

**Comment by jkroepke** [comment]
Could you please enable the debug listener via `--debug.pprof`?

Then, if the deadlock comes up, please open the url http://localhost:9001/debug/pprof/goroutine?debug=2 and save the output to a file. It would help me more then a single screenshot.

**Comment by ihipop** [comment]
> Could you please enable the debug listener via `--debug.pprof`?
> 
> Then, if the deadlock comes up, please open the url http://localhost:9001/debug/pprof/goroutine?debug=2 and save the output to a file. It would help me more then a single screenshot.

[goroutine.txt](https://github.com/jkroepke/openvpn-auth-oauth2/files/14368948/goroutine.txt)


I don't know when the hang will happen, maybe hours or days, so, the code line number of the pprof is against this tree  https://github.com/ihipop/openvpn-auth-oauth2/tree/df0f2e5c4ec873d6a451de5ed1ac53d1ed984b32

**Comment by ihipop** [comment]
> My guess is the main reason is that `commandResponseCh` is not being read, because the only reader is invoked by `SendCommand` if you don't send any command, then there is no reader, then, it blocks and blocks the message reader which hangs the hole program this will happen so if you receive a message [that is not switched here](https://github.com/jkroepke/openvpn-auth-oauth2/blob/54559230c50c74916de570c3be933dfd43933dfc/internal/openvpn/handler.go#L104-L133), it will block I'm debugging what message it is, and I will pull a PR if I find something
> 
> discussion is welcome

I can mostly confirm this is the problem , I can confirm it event without the pprof dump 

![image](https://github.com/jkroepke/openvpn-auth-oauth2/assets/423077/5fc5da25-c315-46af-b44a-b8c0b15668b1)

the size of `commandResponseCh` grows until it comes to 10, this explains why the hang of time-lapse/interval is unstable because it need client activities to triger

a frequently `remote-exit` message speedup the progress

the root cause is you fallback some message ,for example `>NOTIFY:info,remote-exit,EXIT`,
into `commandResponseCh` 
which has only a reader active when you send command

this message will only happen when server is in UDP mode and `explicit-exit-notify` is enabled

a quick fix is to drop this message ,but what about the other messages we don't know?

I suggest a new channel that receives this un-wanted message and dump it to the log?

any idea ?

is a PR welcome?

**Comment by jkroepke** [comment]
A PR is welcome.

A test should be mandatory which cover this scenario.


Dont fully understand the issue. I have enabled explicit-exit-noticy local development for long time, but I'm
unable to verify this.

**Comment by ihipop** [comment]
this time it's about `>NOTIFY`
what about the other message that we don't know?

the problem is that `c.commandResponseCh` should only receive a message that you expected, because you will only read the chan when you are sending a command

a buffer size of 0 should be set instead of 0 to make this problem to be exposed more quickly
