### ISSUE TITLE
Refactor Google Teams sync

### ISSUE THREAD

**Issue by jkroepke** [jkroepke/openvpn-auth-oauth2#195]
### Problem Statement

Google Teams Sync currently depends on the Google Admin Directory API.

This is not necessary, since Google provides the information via Cloud Identity API, too. 

Cloud Identity API doesn't require a dedicated Service Account. It also remove dependencies against the Google SDK which is currently used in `Default Application Credential` scenarios.

/cc @Pionerd 

### Proposed Solution

The OAuth2 scope `https://www.googleapis.com/auth/cloud-identity.groups.readonly`  would sufficient to retrieve the the information with the users AccessToken.

* https://cloud.google.com/identity/docs/reference/rest#rest-resource:-v1.groups.memberships
* https://cloud.google.com/identity/docs/reference/rest/v1/groups.memberships/searchDirectGroups

Ref: https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/google/#configure-team-sync-for-google-oauth

### Additional information

Example Implementation:

https://github.com/grafana/grafana/blob/110028706a160af8c66672d06554f616d660d82c/pkg/login/social/connectors/google_oauth.go#L253-L298

**Comment by Pionerd** [comment]
Thanks for letting me know Grafana now supports this. I will test that also. Please let me know if you need me to test an implementation on your end

**Comment by jkroepke** [comment]
If you could test this: https://github.com/jkroepke/openvpn-auth-oauth2/actions/runs/8031022343/artifacts/1272012950

it would be great. 

Updated docs: https://github.com/jkroepke/openvpn-auth-oauth2/blob/new-google-grousp/docs/Providers.md#restrict-auth-to-specific-google-groups-in-your-domain-optional

**Comment by Pionerd** [comment]
Tested it, works like a charm. This makes things so much easier!
