### ISSUE TITLE
When trying to use groups in plugin, having PANIC

### ISSUE THREAD

**Issue by DenVilk** [jkroepke/openvpn-auth-oauth2#205]
### Current Behavior

When I'm trying to connect to VPN server with setted up openvpn-auth-oauth2 (there is goauthentik issuer connected), getting panic.

### Expected Behavior

Don't get panic error

### Steps To Reproduce

```Markdown
1. Setup openvpn
2. Setup openvpn-auth-oauth2
3. Connect Authentik as IDP
4. Setup groups in openvpn-auth-oauth2
5. Get panic!
```

### Environment

- openvpn-auth-oauth2 Version: 1.19.0
- OpenVPN Server Version: 2.6.9
- Server OS: Ubuntu
- OpenVPN Client (flavor, OS): TunnelBlick 4.0.0beta16 (build 5960)
- OIDC Provider: [Authentik](https://github.com/goauthentik/authentik)

### openvpn-auth-oauth2 logs

```shell
time=2024-03-03T11:42:36.314Z level=ERROR msg="http: panic serving 146.120.15.197:54447: runtime error: invalid memory address or nil pointer dereference\ngoroutine 5 [running]:\nnet/http.(*conn).serve.func1()\n\tnet/http/server.go:1898 +0xbe\npanic({0x7fcaf9f0a800?, 0x7fcafa25fd10?})\n\truntime/panic.go:770 +0x132\ngithub.com/jkroepke/openvpn-auth-oauth2/internal/oauth2/providers/generic.(*Provider).CheckGroups(0xc000034388?, 0x7fcaf984e225?)\n\tgithub.com/jkroepke/openvpn-auth-oauth2/internal/oauth2/providers/generic/check.go:43 +0x22\ngithub.com/jkroepke/openvpn-auth-oauth2/internal/oauth2/providers/generic.(*Provider).CheckUser(0xc0000c3408, {0xc000034528?, 0x7fcaf984dfe5?}, {{0x6, 0x1, {0xc000195130, 0x10}, {0x0, 0x0}, {0x0, ...}}, ...}, ...)\n\tgithub.com/jkroepke/openvpn-auth-oauth2/internal/oauth2/providers/generic/check.go:23 +0x5f\ngithub.com/jkroepke/openvpn-auth-oauth2/internal/oauth2.(*Provider).Handler.(*Provider).oauth2Callback.func3.1({0x7fcaf9f903a0, 0xc0001149a0}, 0x1?, 0xc00006c000, {0x7fcaf9f90c80?, 0xc000181710?}, {0xc00012219a?, 0x20?})\n\tgithub.com/jkroepke/openvpn-auth-oauth2/internal/oauth2/handler.go:205 +0x5e8\ngithub.com/zitadel/oidc/v3/pkg/client/rp.CodeExchangeHandler[...].func1(0xc0001b0360)\n\tgithub.com/zitadel/oidc/v3@v3.13.0/pkg/client/rp/relying_party.go:529 +0x7a7\nnet/http.HandlerFunc.ServeHTTP(0x7fcaf9f8c880?, {0x7fcaf9f903a0?, 0xc0001149a0?}, 0xc0000f2640?)\n\tnet/http/server.go:2166 +0x29\ngithub.com/jkroepke/openvpn-auth-oauth2/internal/oauth2.(*Provider).Handler.(*Provider).oauth2Callback.func3({0x7fcaf9f903a0, 0xc0001149a0}, 0xc0001b0240)\n\tgithub.com/jkroepke/openvpn-auth-oauth2/internal/oauth2/handler.go:231 +0x807\nnet/http.HandlerFunc.ServeHTTP(0xc0001296c0?, {0x7fcaf9f903a0?, 0xc0001149a0?}, 0x7fcaf9b43afa?)\n\tnet/http/server.go:2166 +0x29\nnet/http.(*ServeMux).ServeHTTP(0x7fcaf98ad079?, {0x7fcaf9f903a0, 0xc0001149a0}, 0xc0001b0240)\n\tnet/http/server.go:2683 +0x1ad\nnet/http.serverHandler.ServeHTTP({0xc000024360?}, {0x7fcaf9f903a0?, 0xc0001149a0?}, 0x6?)\n\tnet/http/server.go:3137 +0x8e\nnet/http.(*conn).serve(0xc000226000, {0x7fcaf9f90c80, 0xc000024270})\n\tnet/http/server.go:2039 +0x5e8\ncreated by net/http.(*Server).Serve in goroutine 20\n\tnet/http/server.go:3285 +0x4b4"
time=2024-03-03T11:42:36.391Z level=INFO msg="deny OpenVPN client cid 6, kid 1" ip=146.120.15.197:56439 cid=6 kid=1 common_name=denvilk
time=2024-03-03T11:42:36.391Z level=DEBUG msg="client-deny 6 1 \"client rejected\""
```

**Comment by jkroepke** [comment]
panic reference:

https://github.com/jkroepke/openvpn-auth-oauth2/blob/09de39ac8f6d661cb5f0314460c85eaf13b9cf9c/internal/oauth2/providers/generic/check.go#L43

It seems, this is happening, because I do not get an id_token from Authentik. However I panic should never happens.

I will take an look to the panic here, but It might not solve your problem. openvpn-auth-oauth2 required an id_token, that normally comes from the SSO provider. But it seems like that Authentik wont provide one.

**Comment by DenVilk** [comment]
@jkroepke , how openvpn-auth-oauth2 does get id_token? 
It tries to get authorization code and then change this code to id_token? Or other way?

**Comment by DenVilk** [comment]
Because I tried to test Authentik OIDC with [OIDC Debugger](https://openidconnect.net/) and I get there id_token

**Comment by DenVilk** [comment]
And as I mentioned, it panics only when I'm using groups in openvpn-auth-oauth2

**Comment by jkroepke** [comment]
> it panics only when I'm using groups in openvpn-auth-oauth2

Thats expected, Because I use the id_token only for validation, e.g. groups, roles.

I implement to nil checks that should prevent panics. Could you test them?

https://github.com/jkroepke/openvpn-auth-oauth2/actions/runs/8130566610/artifacts/1292827388

**Comment by DenVilk** [comment]
Now I got this 

```
time=2024-03-03T13:46:13.341Z level=WARN msg="provider did not return a id_token. Validation of user data is not possible." ip=146.120.15.197:51450 cid=9 kid=1 session_id=anOYdsohxd2Wqf8A common_name=denvilk
```

> In worst case, I need the id_token. To reproduce the issue.

Can I get your telegram to send it there? Or you can send message on my with my Github username

**Comment by jkroepke** [comment]
Hm

> In worst case, I need the id_token. To reproduce the issue.

In this case it wont help, because I implement 2 conditions

https://github.com/jkroepke/openvpn-auth-oauth2/blob/aff99a7bb1fdedf1aaf482faae7ccd842f6f37cf/internal/oauth2/providers/generic/user.go#L19-L26

One of them is the error you did get. It appears, if no id_token was given (before parsing). 

The second one appears if a id_token was given, but not parsable. 

There are 2 possibilities:

- OIDC Debugger behave differently then go oauth2 library. Did you configure any scopes?
- Authentik returns an id_token, but its getting ignored.

**Comment by DenVilk** [comment]
I didn't configured any scopes.
But what flow you are use to get tokens? 
As I understood OIDC Debugger send 2 main requests:
1) with grant_type=code
2) change this code for access token and id_token

On the second request Authentik sends response in format:

```json
{
  "access_token": "",
  "token_type": "Bearer",
  "expires_in": 300,
  "id_token": ""
}
```

**Comment by jkroepke** [comment]
> But what flow you are use to get tokens?

The [OAuth Authorization Code Flow](https://curity.io/resources/learn/oauth-code-flow/) is used in general. The OIDC Debugger may use the same.

In openvpn-auth-oauth2 any logic around OIDC is handled by https://github.com/zitadel/oidc which is using https://github.com/golang/oauth2 to retrieve the token.

I have have to setup an own Authentik server to go into this.

**Comment by DenVilk** [comment]
> In openvpn-auth-oauth2 any logic around OIDC is handled by https://github.com/zitadel/oidc which is using https://github.com/golang/oauth2 to retrieve the token.

I've tried same OIDC Debugger with Zitadel and it works the same as Authentik.

> I have have to setup an own Authentik server to go into this.

Okey, I will wait your message :)

**Comment by jkroepke** [comment]
I was not able to reproduce it.

I setup 

* Authentik with docker compose https://docs.goauthentik.io/docs/installation/docker-compose using version 2024.2.1.
* an application using the wizard
* an dedicated user and group.
* I had to configure `CONFIG_OAUTH2_AUTHORIZE__PARAMS="prompt=consent"`, otherwise I got an error that an user consent is required.

everything works as expected. I also did not get this mesage:

> time=2024-03-03T13:46:13.341Z level=WARN msg="provider did not return a id_token. Validation of user data is not possible." ip=146.120.15.197:51450 cid=9 kid=1 session_id=anOYdsohxd2Wqf8A common_name=denvilk

**Comment by DenVilk** [comment]
Can you give your config file for test? May be I have mistakes in my configuration

**Comment by jkroepke** [comment]
Here is my config for openvpn-auth-oauth2 (I have some feature enabled to always test some features)

Related to Authentik (which runs on `http://localhost:9000/`), the values are used:

```
CONFIG_HTTP_SECRET=...
CONFIG_OAUTH2_AUTHORIZE__PARAMS=prompt=consent
CONFIG_OAUTH2_CLIENT_ID=...
CONFIG_OAUTH2_CLIENT_SECRET=...
CONFIG_OAUTH2_ISSUER=http://localhost:9000/application/o/openvpn-auth-oauth2/
CONFIG_OAUTH2_REFRESH_ENABLED=true
CONFIG_OAUTH2_REFRESH_SECRET=...
CONFIG_OAUTH2_VALIDATE_GROUPS=openvpn
CONFIG_OPENVPN_ADDR=tcp://127.0.0.1:8081
CONFIG_OPENVPN_PASSWORD=password
```

**Comment by DenVilk** [comment]
I don't understand how did you do this, but now all works...

Thank you <3
