### ISSUE TITLE
Pass-Through : Send welcome message to client

### ISSUE THREAD

**Issue by GB-G-IT** [jkroepke/openvpn-auth-oauth2#219]
### Problem Statement

When using the passthrough fonctionnality, the passthrough server don't transmit the welcome message send by the OpenVPN Management Interface.
For manual connection, it can be a bit confusing.
For script connection, it can be blocking because of the script waiting the welcome message, or the end of it, and never receive it.

### Proposed Solution

In internal/openvpn/passthrough.go
On connection to Management Interface, read input and send it to client

### Additional information

Example : 
Following script is used to send command to OpenVPN Management Interface (Component of https://github.com/d3vilh/openvpn-ui) : 
https://github.com/d3vilh/openvpn-server-config/blob/main/server/mi/client.go#L98

At line 98, it read the welcome message before sending command, but never receive it from the PassThrough 
`buf := bufio.NewReader(conn)
	buf.ReadString('\n') //read welcome message
	err = SendCommand(conn, cmd)`

**Comment by jkroepke** [comment]
Thanks for the report. It should fixed in the next version

**Comment by jkroepke** [comment]
Additional fixes may required for the UI: https://github.com/jkroepke/openvpn-auth-oauth2/pull/225
