### ISSUE TITLE
Permission denied after installing 1.19.3

### ISSUE THREAD

**Issue by Pionerd** [jkroepke/openvpn-auth-oauth2#226]
### Current Behavior

Mar 25 10:50:29 <hostname> systemd[67054]: openvpn-auth-oauth2.service: Failed to execute /usr/bin/openvpn-auth-oauth2: Permission denied

### Expected Behavior

Everything running OK

### Steps To Reproduce

```Markdown
Upgrade from 1.19.1 to 1.19.3
```

### Environment

- openvpn-auth-oauth2 Version:
- OpenVPN Server Version:
- Server OS:
- OpenVPN Client (flavor, OS):
- OIDC Provider:

### openvpn-auth-oauth2 logs

```shell
Mar 25 10:50:29 shared-hub-vpn-gateway systemd[67054]: openvpn-auth-oauth2.service: Failed to execute /usr/bin/openvpn-auth-oauth2: Permission denied
```

### Anything else?

Switching back to 1.19.1 mitigates the issue

**Comment by jkroepke** [comment]
Isn't there a executable bit on `/usr/bin/openvpn-auth-oauth2`?

**Comment by Pionerd** [comment]
That is not what seems to be the issue:

```
root@shared-hub-vpn-gateway:/etc/openvpn-auth-oauth2# ls -al /usr/bin/openvpn-auth-oauth2 
-rwxr-xr-x 1 root root 11963024 Mar  3 13:33 /usr/bin/openvpn-auth-oauth2
root@shared-hub-vpn-gateway:/etc/openvpn-auth-oauth2# dpkg -i /tmp/openvpn-auth-oauth2_1.19.3_linux_amd64.deb 
(Reading database ... 132755 files and directories currently installed.)
Preparing to unpack .../openvpn-auth-oauth2_1.19.3_linux_amd64.deb ...
Unpacking openvpn-auth-oauth2 (1.19.3) over (1.19.1) ...
Setting up openvpn-auth-oauth2 (1.19.3) ...
root@shared-hub-vpn-gateway:/etc/openvpn-auth-oauth2# ls -al /usr/bin/openvpn-auth-oauth2 
-rwxr-xr-x 1 root root 10285316 Mar 23 09:41 /usr/bin/openvpn-auth-oauth2
root@shared-hub-vpn-gateway:/etc/openvpn-auth-oauth2# systemctl stop openvpn@server && systemctl restart openvpn-auth-oauth2 && systemctl start openvpn@server
HANGS^C
root@shared-hub-vpn-gateway:/etc/openvpn-auth-oauth2# journalctl -flu openvpn-auth-oauth2 --no-pager
Mar 25 11:16:45 shared-hub-vpn-gateway systemd[1]: openvpn-auth-oauth2.service: Scheduled restart job, restart counter is at 3.
Mar 25 11:16:45 shared-hub-vpn-gateway systemd[1]: Stopped OpenVPN authenticator.
Mar 25 11:16:45 shared-hub-vpn-gateway systemd[1]: Started OpenVPN authenticator.
Mar 25 11:16:46 shared-hub-vpn-gateway systemd[67594]: openvpn-auth-oauth2.service: Failed to execute /usr/bin/openvpn-auth-oauth2: Permission denied
Mar 25 11:16:46 shared-hub-vpn-gateway systemd[67594]: openvpn-auth-oauth2.service: Failed at step EXEC spawning /usr/bin/openvpn-auth-oauth2: Permission denied
Mar 25 11:16:46 shared-hub-vpn-gateway systemd[1]: openvpn-auth-oauth2.service: Main process exited, code=exited, status=203/EXEC
```

**Comment by jkroepke** [comment]
I have to change the build a bit to preserve the compatibility with FreeBSD. It seems like I'm hitting some systemd shenanigans here.

**Comment by jkroepke** [comment]
I have some issues with reproducing the issue. Do you have AppArmor enabled on Ubuntu? Are you seen some denies? On my system, AppArmor denies are visible inside audit log, reachable via `dmesg`.

**Comment by Pionerd** [comment]
This particular example is coming from a fairly straightforward VM in GCP. We did not change (or install) anything related to AppArmor. I do however see some AppArmor messages, but not related to VPN.

**Comment by xzcccc** [comment]
hi, I also encountered the same problem.

**Comment by jkroepke** [comment]
I have only a arm64 machine with Ubuntu 22.04 where the issue may not happen. Seems like there is an newer Feature at Debian 12.

**Comment by jkroepke** [comment]
I was able to reproduce the issue.

**Comment by jkroepke** [comment]
Could you please check this release? https://github.com/jkroepke/openvpn-auth-oauth2/releases/tag/v1.20.0-rc.1

**Comment by xzcccc** [comment]
> Could you please check this release? https://github.com/jkroepke/openvpn-auth-oauth2/releases/tag/v1.20.0-rc.1

This version can execute openvpn-auth-oauth2, but I encountered new problems when systemctl start openvpn-auth-oauth2 ...

```
Mar 29 11:07:11 PC openvpn-auth-oauth2[57919]: time=2024-03-29T11:07:11.858+08:00  level=ERROR msg="error http listener: tls.LoadX509KeyPair: open /etc/openvpn-auth-oauth2/server.crt: permission denied"

# ls -al /etc/openvpn-auth-oauth2/server.crt
-rw-r--r-- 1 root openvpn-auth-oauth2 3632 Mar 28 17:47 /etc/openvpn-auth-oauth2/server.crt
```

**Comment by jkroepke** [comment]
After got access to an real VM, i could identify additional bugs.

https://github.com/jkroepke/openvpn-auth-oauth2/releases/tag/v1.20.0-rc.3 should work now.

**Comment by jkroepke** [comment]
Fixed in https://github.com/jkroepke/openvpn-auth-oauth2/releases/tag/v1.20.0
