### ISSUE TITLE
Login page languages

### ISSUE THREAD

**Issue by raivis-ragis** [jkroepke/openvpn-auth-oauth2#228]
### Problem Statement

Current implementation has all the text for end user login page as static strings hardcoded in english and if you want to localize it for another language, you have to edit/patch the code

### Proposed Solution

- Implement localization options for login template - have default strings for english and where possible, read from laguage config files (with template provided in english)/have multiple language files and set language in config/etc.

### Additional information

I.e. these strings for example:
"title":   "**Access denied**"
"message": fmt.Sprintf("**Error ID: %s\r\nPlease contact your administrator for help.**", errorID)

"title":   "**Access granted**",
"message": "**You can close this window now.**",

### Acceptance Criteria

- [] Can set login page text language

**Comment by jkroepke** [comment]
This is a doc from a upcoming featuree (#229): 

Does it met you expectations?

https://github.com/jkroepke/openvpn-auth-oauth2/blob/ui/docs/Layout%20Customization.md
