### ISSUE TITLE
service not start

### ISSUE THREAD

**Issue by sergiogiuffrida** [jkroepke/openvpn-auth-oauth2#23]
I Follow the Medium guide at https://medium.com/@jkroepke/openvpn-sso-via-oauth2-ab2583ee8477

but when i try to run i got this Error for a missing Config parameter.

I don't know what and how i need to add it.
```
{"level":"error","ts":1695507354.3251116,"msg":"error validating config: openvpn.bypass is nil"}
```

**Comment by jkroepke** [comment]
Hi,

it's an known issue that I found and I'll push and release a fix soon.

The fix is part of #24.

**Comment by sergiogiuffrida** [comment]
may be I found the issue.

on cmd/root.go at line 39: WAS
```
	configFile, _ := f.GetString("configfile")
```
I Canged:
```
	configFile, _ := f.GetString("config")
```
 Also internal/config/config.go line 97 was 
 ```
 f.StringSlice("oauth2.bypass.cn", []string{}, "bypass oauth authentication for CNs. (env: CONFIG_OAUTH2_BYPASS_CN)")
 ```
 ```
f.StringSlice("openvpn.bypass.cn", []string{}, "bypass oauth authentication for CNs. (env: CONFIG_OAUTH2_BYPASS_CN)")
```

**Comment by sergiogiuffrida** [comment]
Sorry you already Fixed! Thanks

**Comment by jkroepke** [comment]
Fixed in https://github.com/jkroepke/openvpn-auth-oauth2/releases/tag/v1.3.0
