### ISSUE TITLE
http listener not started after upgrade

### ISSUE THREAD

**Issue by gollum53** [jkroepke/openvpn-auth-oauth2#239]
### Current Behavior

When I update openvpn-auth-oauth2 from openvpn-auth-oauth2_1.18.0_linux_amd64.deb to openvpn-auth-oauth2_1.20.0_linux_amd64.deb, the configured http listener on port 9000 does not start. It reports it has started in the logs but ss - tulpn reports nothing listening on that port. Reverting to version 1.18 fixes the issue. 

### Expected Behavior

Start the listener normally.

### Steps To Reproduce

```Markdown
Install openvpn-server, install openvpn-auth-oauth2_1.18.0_linux_amd64.deb, configure. Everything works. 
Update openvpn-auth-oauth to openvpn-auth-oauth2_1.20.0_linux_amd64.deb via dpkg -i. Listener wont start. 
Tried also dpkg -r openvpn-auth-oauth2_1.18.0_linux_amd64.deb && dpkg -i openvpn-auth-oauth2_1.20.0_linux_amd64.deb, no luck.
```

### Environment

- openvpn-auth-oauth2 Version: 1.20
- OpenVPN Server Version:  2.6.9
- Server OS: ubuntu 22.04 server.
- OpenVPN Client (flavor, OS): not relevant
- OIDC Provider: custom

**Comment by jkroepke** [comment]
With 1.20 I introduce AppArmor profiles to increase the application security of openvpn-auth-oauth2. It cloud be possible that the profile is configured too strong.

Without any logs, from 

* `journalctl -flu openvpn-auth-oauth2` (maybe it need an additional `systemctl start openvpn-auth-oauth2`)
* `dmesg | grep openvpn`

I can't assist here.

**Comment by plstryagain** [comment]
Tried to run the demo, doesn't work for me either.

Last working version for me is 1.19.1

Didn't dive deep into code but for tls = false shouldn't it just be ListenAndServe here? 🙂

https://github.com/jkroepke/openvpn-auth-oauth2/blob/39487b8e4d17f3812cfde9d68681cafe7d710bf6/internal/httpserver/main.go#L73

**Comment by gollum53** [comment]
I can confirm it works now. Thank you very much.
