### ISSUE TITLE
 With Azure AAD level=WARN msg="oauth2.refresh is enabled, but provider does not return refresh token"

### ISSUE THREAD

**Issue by freeddser** [jkroepke/openvpn-auth-oauth2#240]
### Current Behavior

When I connected the OpenVPN, it can not get the refresh token
 level=WARN msg="oauth2.refresh is enabled, but provider does not return refresh token"

my setting for this
CONFIG_OAUTH2_SCOPES=openid profile email offline_access

### Expected Behavior

hope it can return the refresh token

### Environment

CONFIG_OAUTH2_REFRESH_ENABLED=true
 CONFIG_OAUTH2_REFRESH_EXPIRES=8h
 CONFIG_OAUTH2_REFRESH_SECRET=the secret
CONFIG_OAUTH2_REFRESH_USE__SESSION__ID=true
CONFIG_OPENVPN_AUTH__TOKEN__USER=true

OpenVPN 2.6.10 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] [DCO]

### openvpn-auth-oauth2 logs

```shell
level=WARN msg="oauth2.refresh is enabled, but provider does not return refresh token"
```

**Comment by jkroepke** [comment]
It could be possible that your OIDC provide doesn't provide refresh tokens?

At openvpn-auth-oauth2  site you can disable the check with `oauth2.refresh.validate-user`

**Comment by freeddser** [comment]
> It could be possible that your OIDC provide doesn't provide refresh tokens? As I know, with default configuration, Azure AD is able to issue refresh tokens.
> 
> At openvpn-auth-oauth2 site you can disable the check with `--oauth2.refresh.validate-user=false`

CONFIG_OAUTH2_REFRESH_EXPIRES=8h
in OpenVPN server.conf
auth-gen-token 28800 external-auth


Thank you for getting back to me. The current issue is that I have set an expiration time of 8 hours,
But it automatically disconnected after an hour. I looked at the log prompt reauth, then failed. then I need to re-login with Azure account.

Does the program initiate this hourly reauth?

**Comment by freeddser** [comment]
> > Does the program initiate this hourly reauth?
> 
> No, its an OpenVPN default. And can be controlled with the parameter `reneg-sec` which is 3600 by default (1 hour).
> 
> Read more here: https://openvpn.net/community-resources/reference-manual-for-openvpn-2-6/

thanks

**Comment by freeddser** [comment]
I added the reneg-sec 28800 in the client.ovpn for this issues
