### ISSUE TITLE
Logs

### ISSUE THREAD

**Issue by raivis-ragis** [jkroepke/openvpn-auth-oauth2#243]
### Problem Statement

I'm trying to properly manage openvpn-server and openvpn-auth-oauth2 logs and trying to connect both of them.
Openvpn-server has client IP adress data and openvpn-auth-oauth2 has cid, but there's no way to connect those log lines with openvpn-auth-oauth2 log lines - openvpn-server doesn't have a log line with both cid and IP and openvpn-auth-oauth2 doesn't have any log entry with IP. 

Would it be possible, to add client IP address (in example: x.y.z.203) and maybe also port (in example: 51552) to openvpn-auth-oauth2 log lines? at least in one of them, preferrably 1st openvpn-auth-oauth2 log line: "msg="new client connection" cid=617 kid=1 common_name=....". Would be awesome if all the log entries would have IP, but I can also deal with 1 - then I can tie openvpn-server entries which start with IP, with openvpn-auth-oauth2 entries.

Here's an (redacted) current log example:

> Apr  3 14:26:25 openvpn ovpn-server[27936]: x.y.z.203:51552 TLS: move_session: dest=TM_ACTIVE src=TM_INITIAL reinit_src=1
> Apr  3 14:26:25 openvpn ovpn-server[27936]: x.y.z.203:51552 TLS: tls_multi_process: initial untrusted session promoted to semi-trusted
> Apr  3 14:26:25 openvpn openvpn-auth-oauth2[95295]: time=2024-04-03T14:26:25.431Z level=INFO msg="new client connection" cid=617 kid=1 common_name=clientname reason=CONNECT
> Apr  3 14:26:25 openvpn openvpn-auth-oauth2[95295]: time=2024-04-03T14:26:25.431Z level=INFO msg="start pending auth" cid=617 kid=1 common_name=clientname reason=CONNECT
> Apr  3 14:26:25 openvpn ovpn-server[27936]: MANAGEMENT: CMD 'client-pending-auth 617 1 "WEB_AUTH::https://vpn.domain.com:9000/oauth2/start?state=Rs_sz...Angy-sM5_Y" 180'
> Apr  3 14:26:25 openvpn ovpn-server[27936]: SENT CONTROL [clientname]: 'AUTH_PENDING,timeout 180' (status=1)
> Apr  3 14:26:25 openvpn ovpn-server[27936]: SENT CONTROL [clientname]: 'INFO_PRE,WEB_AUTH::https://vpn.domain.com:9000/oauth2/start?state=Rs_sz...Angy-sM5_Y' (status=1)
> Apr  3 14:26:25 openvpn ovpn-server[27936]: x.y.z.203:51552 Control Channel: TLSv1.3, cipher TLSv1.3 TLS_AES_256_GCM_SHA384, peer certificate: 2048 bits RSA, signature: RSA-SHA256, peer temporary key: 253 bits X25519
> Apr  3 14:26:25 openvpn ovpn-server[27936]: x.y.z.203:51552 [clientname] Peer Connection Initiated with [AF_INET]x.y.z.203:51552
> Apr  3 14:26:25 openvpn ovpn-server[27936]: x.y.z.203:51552 PUSH: Received control message: 'PUSH_REQUEST'
> Apr  3 14:26:25 openvpn openvpn-auth-oauth2[95295]: time=2024-04-03T14:26:25.794Z level=INFO msg="initialize authorization via oauth2" cid=617 kid=1 common_name=clientname
> Apr  3 14:26:26 openvpn ovpn-server[27936]: x.y.z.203:51552 PUSH: Received control message: 'PUSH_REQUEST'
> Apr  3 14:26:27 openvpn openvpn-auth-oauth2[95295]: time=2024-04-03T14:26:27.043Z level=INFO msg="successful authorization via oauth2" cid=617 kid=1 common_name=clientname idtoken.subject=sV52..mQ idtoken.email="" idtoken.preferred_username=redacted@redacted.com user.subject=sV52..mQ user.preferred_username=redacted@redacted.com
> Apr  3 14:26:27 openvpn openvpn-auth-oauth2[95295]: time=2024-04-03T14:26:27.043Z level=INFO msg="accept OpenVPN client cid 617, kid 1" cid=617 kid=1 common_name=clientname idtoken.subject=sV52..mQ idtoken.email="" idtoken.preferred_username=redacted@redacted.com user.subject=sV52..mQ user.preferred_username=redacted@redacted.com
> Apr  3 14:26:27 openvpn ovpn-server[27936]: MANAGEMENT: CMD 'client-auth 617 1'
> Apr  3 14:26:27 openvpn ovpn-server[27936]: clientname/x.y.z.203:51552 MULTI_sva: pool returned IPv4=10.1.2.3, IPv6=(Not enabled)

### Environment

- openvpn-auth-oauth2 Version:
- OpenVPN Server Version:
- Server OS:
- OpenVPN Client (flavor, OS):

**Comment by raivis-ragis** [comment]
Sorry, I might have been blind and noticed just now that this is exactly what I'm asking for.
But it says default true.. is this a new param with new version?

> --log.vpn-client-ip
>     	log IP of VPN client. Useful to have an identifier between OpenVPN and openvpn-auth-oauth2. (env: CONFIG_LOG_VPN__CLIENT__IP) (default true)

**Comment by jkroepke** [comment]
Sadly, you did not share the version you are using. It's available since v1.19.0
