### ISSUE TITLE
 Required Ports

### ISSUE THREAD

**Issue by KodakMaciel** [jkroepke/openvpn-auth-oauth2#245]
### Problem Statement

Hello!

I would like to know which ports are necessary to be released for oauth to work correctly in conjunction with OpenVPN.

### Environment

- openvpn-auth-oauth2 Version:
- OpenVPN Server Version:
- Server OS:
- OpenVPN Client (flavor, OS):

**Comment by jkroepke** [comment]
Hi, one port of your choice need to be exposed, by default 9000.
