### ISSUE TITLE
FLAG CONFIG_OAUTH2_VALIDATE_COMMON__NAME

### ISSUE THREAD

**Issue by Mubasitkhan99** [jkroepke/openvpn-auth-oauth2#247]
### Current Behavior

Validate common name flag is not working properly as in the logs of oauth the first 2 logs line showing blank common name ill be attaching the logs below and it failed to validate the common name on the other hand if i don't use this flag then first 2 logs doesn't show the common name but on successful authentication it show the common name in the logs

**LOGS WHEN VALIDATE_COMMON_NAME Flag is turned on with idtoken.email**
level=WARN msg="user validation: common_name mismatch: openvpn client is empty" ip=192.168.35.1:58566 cid=2 kid=1 session_id=zSZQiybIkkWLA58z common_name="" idtoken.subject=112549187817525499082 idtoken.email=mubasit.khan@arpatech.com idtoken.preferred_username="" user.subject=112549187817525499082 user.preferred_username="" error_id=91dc984f40fb6d4fef886db14928ece2d92101388e0a2fd7d68f60512876cf8d
level=INFO msg="client disconnected" ip=: cid=2 common_name="" reason=DISCONNECT session_id="" session_state=""

**LOGS WHEN VALIDATE_COMMON_NAME Flag is turned off**

level=INFO msg="client established" ip=192.168.35.1:54232 vpn_ip=10.8.0.3 cid=4 common_name=mubasit.khan reason=ESTABLISHED session_id=UHYdv/QiDjo8fk3j session_state=Initial

### Expected Behavior

Like my Common name should validate with idtoken.email and if validation is completed then should be able to connect

### Environment

- openvpn-auth-oauth2 Version:1.19.1
- OpenVPN Server Version: 2.6.9
- Server OS: Linux Ubuntu
- OpenVPN Client (Windows, OS):
- OIDC Provider: Gsuite

### openvpn-auth-oauth2 logs

```shell
Apr 06 06:11:08 ARP-792 openvpn-auth-oauth2[1019981]: time=2024-04-06T06:11:08.255-04:00 level=INFO msg="accept OpenVPN client cid 3, kid 1" ip=192.168.35.1:55137 cid=3 kid=1 session_id=dK/cFymJt3IzyJd7 common_name="" idtoken.subject=112549187817525499082 idtoken.email=mubasit.khan@arpatech.com idtoken.preferred_username="" user.subject=112549187817525499082 user.preferred_username=""
Apr 06 06:11:13 ARP-792 openvpn-auth-oauth2[1019981]: time=2024-04-06T06:11:13.614-04:00 level=INFO msg="client established" ip=192.168.35.1:55137 vpn_ip=10.8.0.6 cid=3 common_name="" reason=ESTABLISHED session_id=dK/cFymJt3IzyJd7 session_state=Initial
Apr 06 06:12:07 ARP-792 openvpn-auth-oauth2[1019981]: time=2024-04-06T06:12:07.632-04:00 level=INFO msg="client disconnected" ip=192.168.35.1:55137 cid=3 common_name="" reason=DISCONNECT session_id=dK/cFymJt3IzyJd7 session_state=Initial
Apr 06 06:12:14 ARP-792 openvpn-auth-oauth2[1019981]: time=2024-04-06T06:12:14.166-04:00 level=INFO msg="new client connection" ip=192.168.35.1:54232 cid=4 kid=1 common_name="" reason=CONNECT session_id=UHYdv/QiDjo8fk3j session_state=Initial
Apr 06 06:12:14 ARP-792 openvpn-auth-oauth2[1019981]: time=2024-04-06T06:12:14.166-04:00 level=INFO msg="start pending auth" ip=192.168.35.1:54232 cid=4 kid=1 common_name="" reason=CONNECT session_id=UHYdv/QiDjo8fk3j session_state=Initial
Apr 06 06:12:14 ARP-792 openvpn-auth-oauth2[1019981]: time=2024-04-06T06:12:14.840-04:00 level=INFO msg="initialize authorization via oauth2" ip=192.168.35.1:54232 cid=4 kid=1 common_name=""
Apr 06 06:12:16 ARP-792 openvpn-auth-oauth2[1019981]: time=2024-04-06T06:12:16.959-04:00 level=INFO msg="successful authorization via oauth2" ip=192.168.35.1:54232 cid=4 kid=1 session_id=UHYdv/QiDjo8fk3j common_name="" idtoken.subject=112549187817525499082 idtoken.email=mubasit.khan@arpatech.com idtoken.preferred_username="" user.subject=112549187817525499082 user.preferred_username=""
Apr 06 06:12:16 ARP-792 openvpn-auth-oauth2[1019981]: time=2024-04-06T06:12:16.959-04:00 level=INFO msg="accept OpenVPN client cid 4, kid 1" ip=192.168.35.1:54232 cid=4 kid=1 session_id=UHYdv/QiDjo8fk3j common_name="" idtoken.subject=112549187817525499082 idtoken.email=mubasit.khan@arpatech.com idtoken.preferred_username="" user.subject=112549187817525499082 user.preferred_username=""
Apr 06 06:12:23 ARP-792 openvpn-auth-oauth2[1019981]: time=2024-04-06T06:12:23.198-04:00 level=INFO msg="client established" ip=192.168.35.1:54232 vpn_ip=10.8.0.3 cid=4 common_name=mubasit.khan reason=ESTABLISHED session_id=UHYdv/QiDjo8fk3j session_state=Initial
Apr 06 06:12:41 ARP-792 openvpn-auth-oauth2[1019981]: time=2024-04-06T06:12:41.876-04:00 level=INFO msg="client disconnected" ip=192.168.35.1:54232 cid=4 common_name=mubasit.khan reason=DISCONNECT session_id=UHYdv/QiDjo8fk3j session_state=Initial
```

**Comment by jkroepke** [comment]
`CONFIG_OAUTH2_VALIDATE_COMMON__NAME` is not a boolean which requires true or false. Instead it accepts a string value which be any claim from your idtoken.

If you wish to compare the command with the email field, use `CONFIG_OAUTH2_VALIDATE_COMMON__NAME=email`

> but on successful authentication it show the common name in the logs

It sounds like you are using `username-as-common-name`, read the FAQ here what todo here: https://github.com/jkroepke/openvpn-auth-oauth2/wiki/FAQ#username-as-common-name
