### ISSUE TITLE
Can openvpn-auth-oauth2 implement client-connect functionality similar to opevpn

### ISSUE THREAD

**Issue by Scumwong** [jkroepke/openvpn-auth-oauth2#250]
### Problem Statement

I want  to send a message when client connect to opevpn via openvpn-auth-oauth2 .but i can not get the username ,so i wonder if openvpn-auth-oauth2 can trigger a script like openvpn client-connect and dis-client-connect

### Environment

- openvpn-auth-oauth2 Version:1.19.1
- OpenVPN Server Version:2.6.5
- Server OS:ubuntu22
- OpenVPN Client (flavor, OS):openvpn connect

**Comment by jkroepke** [comment]
Its currently not on the Roadmap, instead there is a plan to implement that natively in OpenVPN, see #202
