### ISSUE TITLE
Ios can't log in

### ISSUE THREAD

**Issue by Jinxin231** [jkroepke/openvpn-auth-oauth2#260]
### Problem Statement

openvpn-auth-oauth2 Version: 1.13.0
OpenVPN Server Version: 2.6.8
Server OS: Linux
OpenVPN Client (flavor, OS): openvpn connect/ IOS

There is a configuration file for the same. I can use it to successfully log in on my PC，however, the same configuration returns the error “Access denied” on the IOS

can you help me?

this is config detail
`client
dev tun
proto tcp
remote ###### 11945
resolv-retry 20
resolv-retry infinite
nobind
persist-key
persist-tun
key-direction 1
comp-lzo
verb 3
;cipher AES-256-GCM
<ca>
-----BEGIN CERTIFICATE-----
######
-----END CERTIFICATE-----
</ca>
<cert>
-----BEGIN CERTIFICATE-----
######
-----END CERTIFICATE-----
</cert>
<key>
-----BEGIN PRIVATE KEY-----
######
-----END PRIVATE KEY-----
</key>
key-direction 1
<tls-auth>
-----BEGIN OpenVPN Static key V1-----
######
-----END OpenVPN Static key V1-----
</tls-auth>
<auth-user-pass>
 test-username-123
 ######
</auth-user-pass>`

 

### Environment

- openvpn-auth-oauth2 Version:
- OpenVPN Server Version:
- Server OS:
- OpenVPN Client (flavor, OS):

**Comment by jkroepke** [comment]
cant help you without logs

**Comment by Jinxin231** [comment]
`[May 06, 2024, 17:20:13] START CONNECTION

[May 06, 2024, 17:20:13] ----- OpenVPN Start -----
OpenVPN core 3.8.5connectQA3 ios arm64 64-bit

[May 06, 2024, 17:20:13] OpenVPN core 3.8.5connectQA3 ios arm64 64-bit

[May 06, 2024, 17:20:13] Frame=512/2112/512 mssfix-ctrl=1250

[May 06, 2024, 17:20:13] NOTE: This configuration contains options that were not used:

[May 06, 2024, 17:20:13] Unsupported option (ignored)

[May 06, 2024, 17:20:13] 0 [resolv-retry] [20]

[May 06, 2024, 17:20:13] 1 [resolv-retry] [infinite]

[May 06, 2024, 17:20:13] 2 [persist-key]

[May 06, 2024, 17:20:13] 3 [persist-tun]

[May 06, 2024, 17:20:13] Unused options, probably specified multiple times in the configuration file

[May 06, 2024, 17:20:13] 0 [key-direction] [1]

[May 06, 2024, 17:20:13] EVENT: RESOLVE

[May 06, 2024, 17:20:13] Contacting #.#.#.#:11945 via TCP

[May 06, 2024, 17:20:13] EVENT: WAIT

[May 06, 2024, 17:20:13] Connecting to [#.#.#.#]:11945 (#.#.#.#) via TCP

[May 06, 2024, 17:20:13] EVENT: CONNECTING

[May 06, 2024, 17:20:13] Tunnel Options:V4,dev-type tun,link-mtu 1544,tun-mtu 1500,proto TCPv4_CLIENT,comp-lzo,keydir 1,cipher BF-CBC,auth SHA1,keysize 128,tls-auth,key-method 2,tls-client

[May 06, 2024, 17:20:13] Creds: Username/Password

[May 06, 2024, 17:20:13] Sending Peer Info:
IV_VER=3.8.5connectQA3
IV_PLAT=ios
IV_NCP=2
IV_TCPNL=1
IV_PROTO=990
IV_MTU=1600
IV_CIPHERS=AES-128-CBC:AES-192-CBC:AES-256-CBC:AES-128-GCM:AES-192-GCM:AES-256-GCM:CHACHA20-POLY1305
IV_LZO=1
IV_AUTO_SESS=1
IV_GUI_VER=net.openvpn.connect.ios_3.4.2-5723
IV_SSO=webauth,openurl,crtext
IV_BS64DL=1


[May 06, 2024, 17:20:13] VERIFY OK: depth=1, /CN=Easy-RSA CA, signature: RSA-SHA256

[May 06, 2024, 17:20:13] VERIFY OK: depth=0, /CN=server, signature: RSA-SHA256

[May 06, 2024, 17:20:13] SSL Handshake: peer certificate: CN=server, 2048 bit RSA, cipher: ECDHE-RSA-AES256-GCM-SHA384    TLSv1.2 Kx=ECDH     Au=RSA   Enc=AESGCM(256)            Mac=AEAD


[May 06, 2024, 17:20:13] Session is ACTIVE

[May 06, 2024, 17:20:13] EVENT: GET_CONFIG

[May 06, 2024, 17:20:13] Sending PUSH_REQUEST to server...

[May 06, 2024, 17:20:13] Extending connection timeout from 59 to 180 for pending authentification

[May 06, 2024, 17:20:13] EVENT: AUTH_PENDING timeout 180

[May 06, 2024, 17:20:13] EVENT: INFO WEB_AUTH::https://#.#.#.#:9000/oauth2/start?state=0nGnLrR8Jpp2Mcs84nStNpu7Bn0z_SmGDdEkY1iVpDaTjfsez2k9tDDcIgj9cvfAXxoqX5Rw

[May 06, 2024, 17:20:14] Sending PUSH_REQUEST to server...

[May 06, 2024, 17:20:17] Stop tunnel requested with reason: 1
[May 06, 2024, 17:20:17] EVENT: DISCONNECTED

[May 06, 2024, 17:20:17] EVENT: CORE_THREAD_DONE

[May 06, 2024, 17:20:17] EVENT: DISCONNECT_PENDING

[May 06, 2024, 17:20:17] Raw stats on disconnect:
  BYTES_IN : 3214
  BYTES_OUT : 1669
  PACKETS_IN : 8
  PACKETS_OUT : 9


[May 06, 2024, 17:20:17] Performance stats on disconnect:
  CPU usage (microseconds): 56677
  Network bytes per CPU second: 86154
  Tunnel bytes per CPU second: 0


`

this is my log  @jkroepke

**Comment by Jinxin231** [comment]
server log

`May 06 17:54:29 iZt4ni0kuiwfr63npcjj9bZ openvpn-auth-oauth2[26392]: time=2024-05-06T17:54:29.055+08:00 level=ERROR msg="http: TLS handshake error from #.#.#.#:41754: tls: first record does not look like a TLS handshake"
May 06 17:54:29 iZt4ni0kuiwfr63npcjj9bZ openvpn-auth-oauth2[26392]: time=2024-05-06T17:54:29.657+08:00 level=ERROR msg="http: TLS handshake error from #.#.#.#:41768: tls: first record does not look like a TLS handshake"

**Comment by jkroepke** [comment]
> l=ERROR msg="http: TLS handshake error from 83.97.73.245:41746: tls: first record does not look like a TLS handshake"

Sounds like 

* you have https listener enabled on openvpn-auth-oauth2, but it gets http traffic

OR

* you have https listener disabled on openvpn-auth-oauth2, but it gets https traffic
