### ISSUE TITLE
Multiple OpenVPN services running on VM

### ISSUE THREAD

**Issue by luk-kop** [jkroepke/openvpn-auth-oauth2#276]
### Problem Statement

Hi, I am wondering what is the best solution to use openvpn-auth-oauth2 plugin when running several OpenVPN services on the same VM. In my case, there are separate services for TCP and UDP mode (e.g. config files - `/etc/openvpn/server/tcp.conf` & `/etc/openvpn/server/udp.conf`). At this point, we are using **openvpn-auth-ldap** plugin for user authentication for both OpenVPN services and want to move to OIDC. Is it necessary to run two openvpn-auth-oauth2 daemons separately for both OpenVPN services in my situation?

### openvpn-auth-oauth2 logs

```shell
Not related
```

### Environment

- openvpn-auth-oauth2 Version: 1.21.2
- OpenVPN Server Version: 2.6.10
- Server OS: Linux (Ubuntu 22.04)
- OpenVPN Client (flavor, OS): Linux/Windows/MacOs

**Comment by jkroepke** [comment]
Hi, yes. 

for each VPN instance, openvpn-auth-oauth2 must run as dedicated instance, too.

**Comment by luk-kop** [comment]
Correct, it is possible, I am currently running two OpenVPN server instances (TCP and UDP) on the same AWS EC2 instance. So, for every OpenVPN server - dedicated openvpn-auth-oauth2 must run and expose dedicated base URL for `/oauth2/callback` endpoint? I plan to use MS Entra ID provider, is it necessary to register two Azure applications in my case as well?

**Comment by luk-kop** [comment]
Hi, I finally had a moment to test and some more questions came up :):
1. As a provider I use MS Entra ID, I noticed that when I run openvpn-auth-oauth2 plugin it connects to login.microsoftonline.com endpoint. In my case all traffic to the Internet will be proxied, does openvpn-auth-oauth2 support traffic proxying?
2. Does openvpn-auth-oauth2 expose any healt-check endpoint, e.g. `/health` or `/healthz`? In front of OpenVPN server I have set up Load Balancer and it performs some health-checks. At this point, i check connection to TCP:9000 on OpenVPN server, but this approach produce a lot of log warnings:
![image](https://github.com/jkroepke/openvpn-auth-oauth2/assets/62556816/b59cae20-ddd1-4622-9acf-44e28300b80d)

**Comment by jkroepke** [comment]
> 1. In my case all traffic to the Internet will be proxied, does openvpn-auth-oauth2 support traffic proxying?

No, not yet. But it seems to be possible to implement http proxy via HTTP_PROXY environment variable.

> Does openvpn-auth-oauth2 expose any healt-check endpoint

No, not yet.

> 3. I also noticed that after restarting OpenVPN server service (management interface connection terminated), the openvpn-auth-oauth2 service (deb package) is deactivated

I guess `Restart=always` should help here in the Service section of the unit file. Could you validate this?

**Comment by jkroepke** [comment]
Each OpenVPN services requires an on instances of openvpn-auth-oauth2
