### ISSUE TITLE
openvpn连接openvpn-auth-oauth2+casdoor报错

### ISSUE THREAD

**Issue by lsx1205** [jkroepke/openvpn-auth-oauth2#286]
### Problem Statement

When the client connects to openvpn, casdoor enters the user name and password, indicating that the authorization is successful, but immediately jumps to a new page, openvpn logs show that the virtual ip address has been assigned, and then the connection is successful. However, SIGUSR1[soft,connection-reset] received, client-instance restarting is restarted. What is the cause?

### openvpn-auth-oauth2 logs

```shell
eason=CONNECT session_id="" session_state=""
Jul 22 18:34:45 dev-vpn2 openvpn-auth-oauth2[147944]: time=2024-07-22T18:34:45.768+08:00 level=INFO msg="initialize authorization via oauth2" ip=xxxxxxx:60323 cid=5 kid=1 common_name=""
Jul 22 18:34:47 dev-vpn2 openvpn-auth-oauth2[147944]: time=2024-07-22T18:34:47.027+08:00 level=INFO msg="client disconnected" ip=: cid=5 common_name="" reason=DISCONNECT session_id="" session_state=""
Jul 22 18:34:47 dev-vpn2 openvpn-auth-oauth2[147944]: time=2024-07-22T18:34:47.027+08:00 level=WARN msg="error from token store: value does not exist" ip=: cid=5 common_name="" reason=DISCONNECT session_id="" session_state=""
```

### Environment

- openvpn-auth-oauth2 Version:
- OpenVPN Server Version:
- Server OS:
- OpenVPN Client (flavor, OS):

**Comment by jkroepke** [comment]
> However, SIGUSR1[soft,connection-reset] received, client-instance restarting is restarted. What is the cause?

A builtin OpenVPN feature named tls soft reset which is by default 1 hour. Refer to openvpn `reneg-sec` setting.
