### ISSUE TITLE
openvpn-auth-oauth Where's the log

### ISSUE THREAD

**Issue by lsx1205** [jkroepke/openvpn-auth-oauth2#288]
### Problem Statement

When configuring openvpn-auth-oauth2, I can only configure the log level in the config file, but I don't know where its logs are stored, so I can't collect logs. Now I can only check them through journalctl. Is there any configuration that can specify the log directory?

### openvpn-auth-oauth2 logs

```shell
journalctl -xefu openvpn-auth-oauth2
```

### Environment

- openvpn-auth-oauth2 Version:
- OpenVPN Server Version:
- Server OS:
- OpenVPN Client (flavor, OS):

**Comment by jkroepke** [comment]
openvpn-auth-oauth2 only supports logging to stdout. Log to file is not supported.

If you run openvpn-auth-oauth2 as systemd service, logs should be stored in journald, since systemd capture stdout and store it in systemd.
