### ISSUE TITLE
Openvpn Connect v.3

### ISSUE THREAD

**Issue by sergiogiuffrida** [jkroepke/openvpn-auth-oauth2#29]
Hi,
I'm testing with Openvpn connect 3 as mac client, it not work.
it is supposed to work with Openvpn connect?

**Comment by jkroepke** [comment]
Didn't even know that OpenVPN Connect 3 exists for MacOS.

Reading https://openvpn.net/vpn-server-resources/connecting-to-access-server-with-macos/ it seems like the client is designed for the OpenVPN Access Server. Not sure, if the client works against OpenVPN 2 server.

**Comment by sergiogiuffrida** [comment]
Openvpn Connect is a client for windows/macos which works nice with all openvpn edition.
I using it for more then 2 years with an Openvpn 2.4.4 Server.
this is what i got on openvpn server logs:
```
PUSH: Received control message: 'PUSH_REQUEST'
````
and this what i have on client logs:
```
⏎[Sep 24, 2023, 15:08:03] Creds: Username/Password
⏎[Sep 24, 2023, 15:08:03] SSL Handshake: peer certificate: CN=server, 2048 bit RSA, cipher: TLS_AES_256_GCM_SHA384         TLSv1.3 Kx=any      Au=any   Enc=AESGCM(256)            Mac=AEAD

⏎[Sep 24, 2023, 15:08:03] Session is ACTIVE
⏎[Sep 24, 2023, 15:08:03] EVENT: GET_CONFIG ⏎[Sep 24, 2023, 15:08:03] Sending PUSH_REQUEST to server...
⏎[Sep 24, 2023, 15:08:04] Sending PUSH_REQUEST to server...
⏎[Sep 24, 2023, 15:08:06] Sending PUSH_REQUEST to server...
```

**Comment by jkroepke** [comment]
> How I can logs all events the management interface?

Running with CONFIG_LOG_LEVEL=debug (--log.level=debug) shows you all command between plugin and management interface

**Comment by sergiogiuffrida** [comment]
Found the issue!!!
it Worked when I removed the password file from 
`management 127.0.0.1 8081 password.txt`
with just `management 127.0.0.1 8081`

and Removed from the yaml configfile.

**Comment by jkroepke** [comment]
Could you please try the lastest version?

Yesterday, I figure out some issues if, the management interface has a password enabled. it should fixed in 1.4.0

**Comment by sergiogiuffrida** [comment]
Seams it not received the line from Management interface: 
```
	line, err := c.readMessage()
	if err != nil {
		return err
	}
	fmt.Printf("Received Line %v \n",line)               ### This will not Print anything!
	if strings.HasPrefix(line, "ENTER PASSWORD") {
		if err := c.rawCommand(c.conf.OpenVpn.Password); err != nil {
			return err
		}

		line, err := c.readMessage()
		if err != nil {
			return err
		}

		if !strings.HasPrefix(line, "SUCCESS: password is correct") {
			return errors.New("wrong openvpn management interface password")
		}
	}
```

**Comment by sergiogiuffrida** [comment]
Ok, I can confirm with 1.4.0 Version it works!


Thank you Very much!

**Comment by jkroepke** [comment]
Thanks for the hint that OpenVPN 3 for Mac works fine, I add the client to the compatibility list.
