### ISSUE TITLE
Using native HTTPS support

### ISSUE THREAD

**Issue by FelipeAscensio** [jkroepke/openvpn-auth-oauth2#291]
### Problem Statement

Is it possible to use .pem in Using native HTTPS support?

like this:
CONFIG_HTTP_TLS=true
CONFIG_HTTP_KEY=/etc/letsencrypt/live/***/privkey.pem
CONFIG_HTTP_CERT=/etc/letsencrypt/live/***/cert.pem

### openvpn-auth-oauth2 logs

```shell
Jul 29 14:53:19 sentinel3 systemd[1]: Started openvpn-auth-oauth2.service - OpenVPN authenticator.
Jul 29 14:53:19 sentinel3 openvpn-auth-oauth2[14577]: time=2024-07-29T14:53:19.760Z level=INFO msg="discover oidc auto configuration with provider google for issuer https://accounts.google.com"
Jul 29 14:53:19 sentinel3 openvpn-auth-oauth2[14577]: time=2024-07-29T14:53:19.978Z level=INFO msg="connect to openvpn management interface unix:///run/openvpn/server.sock"
Jul 29 14:53:19 sentinel3 openvpn-auth-oauth2[14577]: time=2024-07-29T14:53:19.978Z level=INFO msg="openvpn-auth-oauth2 started with base url https://***:9000"
Jul 29 14:53:19 sentinel3 openvpn-auth-oauth2[14577]: time=2024-07-29T14:53:19.978Z level=ERROR msg="error http listener: tls.LoadX509KeyPair: open /etc/letsencrypt/live/***/privkey.pem: permission denied"
Jul 29 14:53:19 sentinel3 openvpn-auth-oauth2[14577]: time=2024-07-29T14:53:19.978Z level=INFO msg="connection to OpenVPN management interface established."
Jul 29 14:53:19 sentinel3 openvpn-auth-oauth2[14577]: time=2024-07-29T14:53:19.978Z level=INFO msg="shutdown OpenVPN management connection"
Jul 29 14:53:19 sentinel3 systemd[1]: openvpn-auth-oauth2.service: Main process exited, code=exited, status=1/FAILURE
Jul 29 14:53:19 sentinel3 systemd[1]: openvpn-auth-oauth2.service: Failed with result 'exit-code'.
```

### Environment

- openvpn-auth-oauth2 Version:
- OpenVPN Server Version:
- Server OS:
- OpenVPN Client (flavor, OS):

**Comment by jkroepke** [comment]
Yes. Just copy the files to /etc/openvpn-auth-oauth2/ and make sure, the unix group openvpn-auth-oauth2 can read the file

**Comment by FelipeAscensio** [comment]
i did it, but same erro

/etc/sysconfig/openvpn-auth-oauth2

CONFIG_HTTP_TLS=true
CONFIG_HTTP_KEY=privkey.pem
CONFIG_HTTP_CERT=cert.pem

root@sentinel3:/etc/openvpn-auth-oauth2#  ls -alh
total 20K
drwxr-x---  2 root openvpn-auth-oauth2 4.0K Jul 29 16:41 .
drwxr-xr-x 97 root root                4.0K Jul 29 14:42 ..
-rw-r--r--  1 root openvpn-auth-oauth2 1.8K Jul 28 18:40 cert.pem
-rw-r-----  1 root openvpn-auth-oauth2 1.6K Jul 21 08:51 config.yaml
-rw-r--r--  1 root openvpn-auth-oauth2 1.7K Jul 28 18:40 privkey.pem

LOG

Jul 29 16:43:03 sentinel3 systemd[1]: Started openvpn-auth-oauth2.service - OpenVPN authenticator.
Jul 29 16:43:03 sentinel3 openvpn-auth-oauth2[14919]: time=2024-07-29T16:43:03.306Z level=INFO msg="discover oidc auto configuration with provider google for issuer https://accounts.google.>
Jul 29 16:43:03 sentinel3 openvpn-auth-oauth2[14919]: time=2024-07-29T16:43:03.484Z level=INFO msg="connect to openvpn management interface unix:///run/openvpn/server.sock"
Jul 29 16:43:03 sentinel3 openvpn-auth-oauth2[14919]: time=2024-07-29T16:43:03.484Z level=INFO msg="openvpn-auth-oauth2 started with base url https://sentinel3.icarotech.com"
Jul 29 16:43:03 sentinel3 openvpn-auth-oauth2[14919]: time=2024-07-29T16:43:03.484Z level=ERROR msg="error http listener: tls.LoadX509KeyPair: open : no such file or directory"
Jul 29 16:43:03 sentinel3 openvpn-auth-oauth2[14919]: time=2024-07-29T16:43:03.484Z level=INFO msg="connection to OpenVPN management interface established."
Jul 29 16:43:03 sentinel3 openvpn-auth-oauth2[14919]: time=2024-07-29T16:43:03.484Z level=INFO msg="shutdown OpenVPN management connection"
Jul 29 16:43:03 sentinel3 systemd[1]: openvpn-auth-oauth2.service: Main process exited, code=exited, status=1/FAILURE

**Comment by FelipeAscensio** [comment]
It worked!

It has to be all the way


CONFIG_HTTP_TLS=true
CONFIG_HTTP_KEY=/etc/openvpn-auth-oauth2/privkey.pem
CONFIG_HTTP_CERT=/etc/openvpn-auth-oauth2/cert.pem
