### ISSUE TITLE
Run https directly

### ISSUE THREAD

**Issue by FelipeAscensio** [jkroepke/openvpn-auth-oauth2#292]
### Problem Statement

Can i run directly in https (443)?

My config:

CONFIG_HTTP_LISTEN=:443

CONFIG_HTTP_TLS=true
CONFIG_HTTP_KEY=/etc/openvpn-auth-oauth2/privkey.pem
CONFIG_HTTP_CERT=/etc/openvpn-auth-oauth2/cert.pem

### openvpn-auth-oauth2 logs

```shell
error:

Jul 29 16:56:09 sentinel3 openvpn-auth-oauth2[15588]: time=2024-07-29T16:56:09.892Z level=ERROR msg="error http listener: error http server listening: listen tcp :443: bind: permission denied"
```

### Environment

- openvpn-auth-oauth2 Version:
- OpenVPN Server Version:
- Server OS:
- OpenVPN Client (flavor, OS):

**Comment by Ecsi1337** [comment]
Same problem, if:
CONFIG_HTTP_TLS=true
CONFIG_HTTP_KEY=server.key
CONFIG_HTTP_CERT=server.crt

root@ubuntu-mini:/etc/openvpn# systemctl daemon-reload
root@ubuntu-mini:/etc/openvpn# systemctl restart openvpn-auth-oauth2
root@ubuntu-mini:/etc/openvpn# systemctl status openvpn-auth-oauth2
× openvpn-auth-oauth2.service - OpenVPN authenticator
     Loaded: loaded (/usr/lib/systemd/system/openvpn-auth-oauth2.service; disabled; preset: enabled)
     Active: failed (Result: exit-code) since Mon 2024-07-29 21:17:09 CEST; 1s ago
   Duration: 259ms
       Docs: https://github.com/jkroepke/openvpn-auth-oauth2
    Process: 12712 ExecStart=/usr/bin/openvpn-auth-oauth2 --config ${CONFIG_FILE} (code=exited, status=1/FAILURE)
   Main PID: 12712 (code=exited, status=1/FAILURE)
        CPU: 55ms

júl 29 21:17:09 ubuntu-mini systemd[1]: Started openvpn-auth-oauth2.service - OpenVPN authenticator.
júl 29 21:17:09 ubuntu-mini openvpn-auth-oauth2[12712]: time=2024-07-29T21:17:09.316+02:00 level=INFO msg="discover oidc auto configuration with provider generic for issuer https://login.microsoftonline.com/259d87a2-7c45-4ee7-b4cb-86605>
júl 29 21:17:09 ubuntu-mini openvpn-auth-oauth2[12712]: time=2024-07-29T21:17:09.537+02:00 level=INFO msg="connect to openvpn management interface unix:/run/openvpn/server.sock"
júl 29 21:17:09 ubuntu-mini openvpn-auth-oauth2[12712]: time=2024-07-29T21:17:09.537+02:00 level=INFO msg="openvpn-auth-oauth2 started with base url https://wsty.ovirt.hu/"
júl 29 21:17:09 ubuntu-mini openvpn-auth-oauth2[12712]: time=2024-07-29T21:17:09.537+02:00 level=ERROR msg="error http listener: tls.LoadX509KeyPair: open server.crt: no such file or directory"
júl 29 21:17:09 ubuntu-mini openvpn-auth-oauth2[12712]: time=2024-07-29T21:17:09.537+02:00 level=INFO msg="connection to OpenVPN management interface established."
júl 29 21:17:09 ubuntu-mini openvpn-auth-oauth2[12712]: time=2024-07-29T21:17:09.537+02:00 level=INFO msg="shutdown OpenVPN management connection"
júl 29 21:17:09 ubuntu-mini systemd[1]: openvpn-auth-oauth2.service: Main process exited, code=exited, status=1/FAILURE
júl 29 21:17:09 ubuntu-mini systemd[1]: openvpn-auth-oauth2.service: Failed with result 'exit-code'.

**Comment by jkroepke** [comment]
@Ecsi1337 Why we say `Same problem`, if the error message is different? Please use absolute paths.

@FelipeAscensio Try this:

```
sudo systemctl edit openvpn-auth-oauth2.service

# add the text below to the editor in the designated section
[Service]
AmbientCapabilities=CAP_NET_BIND_SERVICE

# save the file and reload the service
sudo systemctl daemon-reload
```

**Comment by Ecsi1337** [comment]
These commands didn't help either

Using native HTTPS support
openvpn-auth-oauth2 supports HTTPS out of the box.

CONFIG_HTTP_TLS=true
CONFIG_HTTP_KEY=server.key
CONFIG_HTTP_CERT=server.crt
To set up a self-signed certificate, you can use the command below:

export DOMAIN_NAME=vpn.example.com
openssl req -x509 -newkey rsa:4096 -sha256 -days 3650 -nodes -keyout server.key -out server.crt -subj "/CN=$DOMAIN_NAME" -addext "subjectAltName=DNS:$DOMAIN_NAME"

**Comment by jkroepke** [comment]
@Ecsi1337 https://github.com/jkroepke/openvpn-auth-oauth2/issues/291#issuecomment-2256430271

**Comment by elozev** [comment]
Experiencing the same issue here with running http server on port 80 or 443.
```
Aug 16 14:18:01 ip-10-50-49-20 openvpn-auth-oauth2[5812]: time=2024-08-16T14:18:01.524Z level=INFO msg="manually configure oauth2 provider with provider generic and providerConfig ht>
Aug 16 14:18:01 ip-10-50-49-20 openvpn-auth-oauth2[5812]: time=2024-08-16T14:18:01.524Z level=WARN msg="generic provider with manual configuration is used. Validation of user data is>
Aug 16 14:18:01 ip-10-50-49-20 openvpn-auth-oauth2[5812]: time=2024-08-16T14:18:01.524Z level=INFO msg="start HTTP server listener on :80"
Aug 16 14:18:01 ip-10-50-49-20 openvpn-auth-oauth2[5812]: time=2024-08-16T14:18:01.524Z level=INFO msg="connect to openvpn management interface tcp://127.0.0.1:7505"
Aug 16 14:18:01 ip-10-50-49-20 openvpn-auth-oauth2[5812]: time=2024-08-16T14:18:01.524Z level=INFO msg="openvpn-auth-oauth2 started with base url http://openvpn-my-server.com>
Aug 16 14:18:01 ip-10-50-49-20 openvpn-auth-oauth2[5812]: time=2024-08-16T14:18:01.525Z level=ERROR msg="error http listener: error http server listening: listen tcp :80: bind: permi>
Aug 16 14:18:01 ip-10-50-49-20 openvpn-auth-oauth2[5812]: time=2024-08-16T14:18:01.525Z level=INFO msg="connection to OpenVPN management interface established."
Aug 16 14:18:01 ip-10-50-49-20 openvpn-auth-oauth2[5812]: time=2024-08-16T14:18:01.525Z level=INFO msg="shutdown OpenVPN management connection"
```

Some observations I've had are:
1. I'm able to start the HTTP server successfully if I run: `openvpn-auth-oauth2 --config /etc/openvpn-auth-oauth2/config.yaml` and successfully bind to port 80 or 443, where the `config.yaml` looks like this:
```
  http:
   baseurl: http://openvpn-intranet-01.moneyfarm.com
   listen: :80
   secret: ...
   tls: false
  oauth2:
    client:
      id: ...
      secret: ...
    endpoint:
      discovery: ...
      auth: ...
      token: ...
    issuer: ...
    provider: generic
    scopes:
      - openid
      - profile
      - email
  openvpn:
   addr: tcp://127.0.0.1:7505  # This is overridden by /etc/sysconfig/openvpn-auth-oauth2
   password: ...
```
And my `/etc/sysconfig/openvpn-auth-oauth2` has the following contents:
```
# ------------------------------------------------------------------------------
# openvpn-auth-oauth2 Environment File
# ------------------------------------------------------------------------------
# This file is sourced by the openvpn-auth-oauth2 systemd service. It contains
# environment variable settings that are used when the service is started via
# systemd.
#
# Please note:
# 1. This environment file is only utilized when openvpn-auth-oauth2 is started
#    as a systemd service.
# 2. Settings defined in this file will override the corresponding settings
#    defined in the main configuration file of openvpn-auth-oauth2.
#
# To apply changes to this file, you must reload the systemd service by running:
#    sudo systemctl daemon-reload
#    sudo systemctl restart openvpn-auth-oauth2
#
# For more information, please refer to the documentation:
# https://github.com/jkroepke/openvpn-auth-oauth2/wiki/Configuration
#
# ------------------------------------------------------------------------------
# Environment Variables
# ------------------------------------------------------------------------------

## CONFIG_FILE is the path to the configuration file. Defaults to /etc/openvpn-auth-oauth2/config.yaml
CONFIG_FILE=/etc/openvpn-auth-oauth2/config.yaml

#CONFIG_OPENVPN_ADDR=unix:///run/openvpn/server.sock

#CONFIG_OPENVPN_ADDR=127.0.0.1:7505
#CONFIG_OPENVPN_PASSWORD=test123

## Define OIDC related settings
#CONFIG_OAUTH2_ISSUER=https://login.microsoftonline.com/<tenant-id>/v2.0
#CONFIG_OAUTH2_CLIENT_ID=
#CONFIG_OAUTH2_CLIENT_SECRET=
#CONFIG_HTTP_LISTEN=:9000

## Define a random value with 16 or 24 characters
#CONFIG_HTTP_SECRET=

## Define the public http endpoint here.
#CONFIG_HTTP_BASEURL=http://localhost:9000
```

2. @jkroepke I tried what you suggested here https://github.com/jkroepke/openvpn-auth-oauth2/issues/292#issuecomment-2256728970, and even went further to set the `User=root` and `Group=root` and disable the `DynamicUser=false` in the service definition.
```
[Service]
# Run as an unprivileged user with random user id.
DynamicUser=false
User=root
Group=root
SupplementaryGroups=openvpn-auth-oauth2
AmbientCapabilities=CAP_NET_BIND_SERVICE
```

---
## Environment

openvpn-auth-oauth2 Version: `1.22.0`
OpenVPN Server Version: `OpenVPN 2.6.9 x86_64-pc-linux-gnu`
Server OS: `Ubuntu 24.04 LTS`
OpenVPN Client (flavor, OS): N/A

**Comment by jkroepke** [comment]
@elozev Could you please revert the changes in the systemd unit file about user/group and only configure `AmbientCapabilities`

```
[Service]
AmbientCapabilities=CAP_NET_BIND_SERVICE
```

And configure apparmor to allow 


```
echo "capability net_bind_service," > /etc/apparmor.d/local/usr.bin.openvpn-auth-oauth2
```

The AppArmor capability `net_bind_service` is required in addition to start a service below port 1024

**Comment by elozev** [comment]
Thanks @jkroepke, that worked!
