### ISSUE TITLE
openvpn the client restarts abnormally. Procedure

### ISSUE THREAD

**Issue by lsx1205** [jkroepke/openvpn-auth-oauth2#293]
### Problem Statement

After connecting to casdoor with oauth2 plug-in, basically every 50 minutes or so, the client will jump back to the login interface of casdoor, but the authentication expiration time of casdoor is set to 168 hours, and neither openvpn nor oauth2 has a restart record. It is very strange

### openvpn-auth-oauth2 logs

```shell
*
```

### Environment

- openvpn-auth-oauth2 Version: latest
- OpenVPN Server Version: latest
- Server OS:
- OpenVPN Client (flavor, OS): os

**Comment by jkroepke** [comment]
Without logs of openvpn server and openvpn-auth-oauth2, I cant support

**Comment by lsx1205** [comment]
openvpn - log：
:54818 TLS: soft reset sec=3503/3502 bytes=351748/-1 pkts=3096/0
:54818 peer info: IV_VER=3.8.2connect3
:54818 peer info: IV_PLAT=mac
:54818 peer info: IV_NCP=2
:54818 peer info: IV_TCPNL=1
:54818 peer info: IV_PROTO=990
:54818 peer info: IV_MTU=1600
:54818 peer info: IV_CIPHERS=AES-128-CBC:AES-192-CBC:AES-256-CBC:AES-128-GCM:AES-192-GCM:AES-256-GCM:CHACHA20-POLY1305
:54818 peer info: IV_LZO=1
:54818 peer info: IV_AUTO_SESS=1
:54818 peer info: IV_GUI_VER=OCmacOS_3.4.9-4830
:54818 peer info: IV_SSO=webauth,crtext
:54818 TLS: Username/Password authentication deferred for username '' [CN SET]
:54818 Control Channel: TLSv1.3, cipher TLSv1.3 TLS_AES_256_GCM_SHA384, peer temporary key: 253 bits X25519
MANAGEMENT: CMD 'client-pending-auth 12 3 "WEB_AUTH::https://dev-xxxxxx/oauth2/start?state=Ji8QXKc_Pv4juCK1gVtb_OmOD0dVK1ikE_RN9XG0whM5D0K7NMatNrYz7a_H7y1j3a6dkasl5mk6JvJHex-u6egTcavTCtKrkOad00C2QFw" 180'
SENT CONTROL []: 'AUTH_PENDING,timeout 180' (status=1)
SENT CONTROL []: 'INFO_PRE,WEB_AUTH::https://dev-vpn.os.kr36.ink/oauth2/start?state=Ji8QXKc_Pv4juCK1gVtb_OmOD0dVK1ikE_RN9XG0whM5D0K7NMatNrYz7a_H7y1j3a6dkasl5mk6JvJHex-u6egTcavTCtKrkOad00C2QFw' (status=1)
MANAGEMENT: CMD 'client-auth 12 3'
:54818 SENT CONTROL []: 'PUSH_REPLY,auth-tokenSESS_ID' (status=1)


openvpn-auth-oauth2 - log

time=2024-07-30T18:49:32.289+08:00 level=INFO msg="new client reauth" ip=xxxxxxx:54818 cid=12 kid=3 common_name="" reason=REAUTH session_id=1RbZyLfSMre5mq4H session_state=AuthenticatedEmptyUser
time=2024-07-30T18:49:32.289+08:00 level=INFO msg="initiate non-interactive authentication via refresh token" ip=124.128.194.174:54818 cid=12 kid=3 common_name="" reason=REAUTH session_id=1RbZyLfSMre5mq4H session_state=AuthenticatedEmptyUser
time=2024-07-30T18:49:32.496+08:00 level=WARN msg="error from token exchange: error from token exchange: ErrorType=invalid_grant Description=refresh token is invalid, expired or revoked" ip=xxxxxx:54818 cid=12 kid=3 common_name="" reason=REAUTH session_id=1RbZyLfSMre5mq4H session_state=AuthenticatedEmptyUser
time=2024-07-30T18:49:32.496+08:00 level=INFO msg="start pending auth" ip=xxxxxx:54818 cid=12 kid=3 common_name="" reason=REAUTH session_id=1RbZyLfSMre5mq4H session_state=AuthenticatedEmptyUser
time=2024-07-30T18:49:32.700+08:00 level=INFO msg="initialize authorization via oauth2" ip=xxxxxx:54818 cid=12 kid=3 common_name=""
time=2024-07-30T18:49:38.714+08:00 level=INFO msg="successful authorization via oauth2" ip=xxxxxx:54818 cid=12 kid=3 session_id=1RbZyLfSMre5mq4H common_name="" idtoken.subject=7d3f45f8-b638-49dc-81aa-bd126f158bf4 idtoken.email=lusheng@test.com idtoken.preferred_username="" user.subject=7d3f45f8-b638-49dc-81aa-bd126f158bf4 user.preferred_username=""
time=2024-07-30T18:49:38.714+08:00 level=INFO msg="accept OpenVPN client cid 12, kid 3" ip=xxxxx:54818 cid=12 kid=3 session_id=1RbZyLfSMre5mq4H common_name="" idtoken.subject=7d3f45f8-b638-49dc-81aa-bd126f158bf4 idtoken.email=lusheng@test.com idtoken.preferred_username="" user.subject=7d3f45f8-b638-49dc-81aa-bd126f158bf4 user.preferred_username=""
time=2024-07-30T18:51:48.581+08:00 level=WARN msg="invalid state: invalid state: expired after 2 minutes, issued at: 2m16.581343172s"
time=2024-07-30T18:51:48.618+08:00 level=WARN msg="invalid state: invalid state: expired after 2 minutes, issued at: 2m16.618329931s"
time=2024-07-30T18:51:48.654+08:00 level=WARN msg="invalid state: invalid state: expired after 2 minutes, issued at: 2m16.654549658s"
time=2024-07-30T18:51:49.662+08:00 level=WARN msg="invalid state: invalid state: expired after 2 minutes, issued at: 2m17.662972757s"
time=2024-07-30T18:51:50.671+08:00 level=WARN msg="invalid state: invalid state: expired after 2 minutes, issued at: 2m18.671468377s"

Can you see that

**Comment by jkroepke** [comment]
> TLS: soft reset

OpenVPN has a setting called reneg-sec. the default value is 3600. In a standard configuration, the OpenVPN server (and client) will terminate the connection after approx 60 Minutes. This is expected and generally supported.

openvpn-auth-oauth2 will used the stored refresh token to re-authenticate the user. However, your IDP (casdoor?) rejects this, because the refresh token is invalide.

> time=2024-07-30T18:49:32.496+08:00 level=WARN msg="error from token exchange: error from token exchange: ErrorType=invalid_grant Description=refresh token is invalid, expired or revoked" ip=xxxxxx:54818 cid=12 kid=3

The message `Description=refresh token is invalid, expired or revoked` is returned by casdoor. What ever you have configured at casdoor, the refresh token is invalid or expired.

Then, openvpn-auth-oauth2 falls back to an interactive authentication.

3 possible solutions:

* Fix casdoor configure (I cant help you here, it seems like the 168 hours settings does not have any effect)
* Set `reneg-sec 0` and `push "reneg-sec 0"` at OpenVPN server config which leads into a less secure connections, since rekeying is disabled
* Set `oauth2.refresh.validate-user` at openvpn-auth-oauth2. This skips calling casdoor on re-authentications.

**Comment by lsx1205** [comment]
thank you

The configuration of casdoor does not have any effect, and the setting of oauth2.refresh.validate-user as openvpn-auth-oauth2 you said is invalid and needs to be a bool value.

log:
,time=2024-07-31T09:32:39.776+08:00 level=ERROR msg="error loading config: error unmarschal config: decoding failed due to the following error(s):\n\ncannot parse 'oauth2.refresh.validate-user' as bool: strconv.ParseBool: parsing \"openvpn-auth-oauth2\": invalid syntax"

**Comment by lsx1205** [comment]
reneg-sec, can not be regarded as 0, is the 7200 I set invalid, or jump about 60 minutes, I changed oauth2.refresh.validate-user to false, is observing
