### ISSUE TITLE
Management Interface ????

### ISSUE THREAD

**Issue by Ecsi1337** [jkroepke/openvpn-auth-oauth2#294]
### Problem Statement

How can I access the management interface and what can I manage there?

### openvpn-auth-oauth2 logs

```shell
.
```

### Environment

- openvpn-auth-oauth2 Version:
- OpenVPN Server Version:
- Server OS:
- OpenVPN Client (flavor, OS):

**Comment by jkroepke** [comment]
There is no management interface
