### ISSUE TITLE
Incorrect documentation

### ISSUE THREAD

**Issue by agarciamtk** [jkroepke/openvpn-auth-oauth2#297]
### Current Behavior

Parameter --openvpn.common-name.environment-variable states in help/documentation that the environment variable associated is CONFIG_OPENVPN_COMMON__NAME_ENVIRONMENT__VARIABLE, but it's currently CONFIG_OPENVPN_COMMON__NAME_ENVIRONMENT__VARIABLE__NAME, otherwise it won't work resulting in the following error in the log: "user validation: common_name mismatch: openvpn client is empty"

--openvpn.common-name.environment-variable string
    	Name of the environment variable in the OpenVPN management interface which contains the common name. If username-as-common-name is enabled, this should be set to 'username' to use the username as common name. Other values like 'X509_0_emailAddress' are supported. See https://openvpn.net/community-resources/reference-manual-for-openvpn-2-6/#environmental-variables for more information. (env: CONFIG_OPENVPN_COMMON__NAME_ENVIRONMENT__VARIABLE) (default "common_name")

### Expected Behavior

Documentation matches environmental variable 

### Steps To Reproduce

```Markdown
As stated by documentation: 
https://github.com/jkroepke/openvpn-auth-oauth2/wiki/FAQ#q-mismatch-openvpn-client-is-empty--username-as-common-name
When username-as-common-name is enabled, --openvpn.common-name.environment-variable should be set, but documentations states an incorrect environment variable

# this won't work
CONFIG_OPENVPN_COMMON__NAME_ENVIRONMENT__VARIABLE=username

# this works
CONFIG_OPENVPN_COMMON__NAME_ENVIRONMENT__VARIABLE__NAME=username
```

### Environment

- openvpn-auth-oauth2 Version: 1.21.4
- OpenVPN Server Version: OpenVPN 2.6.9 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] [DCO]
- Server OS: Ubuntu 24.04 LTS
- OpenVPN Client (flavor, OS): Windows, OpenVPN 2.6.12
- OIDC Provider: Microsoft Entra ID

### openvpn-auth-oauth2 logs

```shell
Aug 05 13:15:44 vpn-openvpn2 openvpn-auth-oauth2[13280]: time=2024-08-05T13:15:44.352Z level=WARN msg="user validation: common_name mismatch: openvpn client is empty" ip=11.22.33.44:53442 cid=0 kid=1 session_id=SESSION common_name="" idtoken.subject=SUBJECT idtoken.email="" idtoken.preferred_username=user@mail.com.ar user.subject=SUBJECT user.preferred_username=user@mail.com.ar error_id=ERRORID
```

**Comment by jkroepke** [comment]
Thank for the report
