### ISSUE TITLE
Documentation: Azure oauth2 scope must include "openid"

### ISSUE THREAD

**Issue by Pavlos1** [jkroepke/openvpn-auth-oauth2#304]
### Problem Statement

First: I like this project a lot, I was considering getting my company to purchase Cisco AnyConnect before I found this and it's really nice to have an open source alternative. I finally managed to get everything set up and I have a suggestion to improve the documentation:

In order for openvpn-auth-oauth2 to work with Azure, it needs to receive an `id_token`. This doesn't happen unless `CONFIG_OAUTH2_SCOPES=openid` is set in `/etc/sysconfig/openvpn-auth-oauth2`. It would help if this information was provided in the wiki. (Maybe it is and I just didn't find it?)

**Comment by jkroepke** [comment]
Hey @Pavlos1 

I really appreciate your donation! I directly convert it to some beer with friends. I'm happy to hear, that this open source project avoids at least one more AnyConnect installation.

You are right. The scope are currently not documented. If unconfigured by used, openvpn-auth-oauth2 choices the correct defaults. #306 will enrich the documents here to cover your case.
