### ISSUE TITLE
How to manipulate Common Name

### ISSUE THREAD

**Issue by D0wn3r** [jkroepke/openvpn-auth-oauth2#324]
### Problem Statement

Hi!
Thank you for this project. I'm implementing it, but I have an issue or a misunderstanding regarding the use of the 'Common Name'.
I'm using the Microsoft provider, and I would like to match the 'Common Name' to the username of the person connecting, so I can assign an IP address, for example.
How can I do that, please?

Thanks!

### openvpn-auth-oauth2 logs

```shell
No need ?
```

**Comment by jkroepke** [comment]
> How can I do that, please?

This is impossible. See https://github.com/jkroepke/openvpn-auth-oauth2/issues/202

**Comment by D0wn3r** [comment]
Ok thank you. Very sad to hear it
