### ISSUE TITLE
Automatically detect auth-token-gen usage

### ISSUE THREAD

**Issue by Laboltus** [jkroepke/openvpn-auth-oauth2#330]
### Problem Statement

I was able to set up Google Workspaces authentication, ttl  in CONFIG_OAUTH2_REFRESH_EXPIRES and the auth-gen-token set to 16 hours. Every 16 hours I see in logs "successful authorization via oauth2" message and the connection remains alive. But after first 16 hours I  see in openvpn logs every reneg-sec interval:
```
--auth-gen-token: auth-token from client expired
```
and in openvpn-auth-oauth2 logs:
```
msg="new client reauth" ip=1.2.3.4:46972 cid=0 kid=2285 common_name="" reason=REAUTH session_id=Ng/0u/uT/qPk1v/R session_state=ExpiredEmptyUser
```

also the connection in Tunnelblick all the time (after first 16 hours) is in AUTH_PENDING state. The connection itself is still working as expected but I'd like to fix this behavior if possible.

### openvpn-auth-oauth2 logs

```shell
openvpn-auth-oauth2 Version: latest
```

### Environment

- openvpn-auth-oauth2 Version:
- OpenVPN Server Version:
- Server OS:
- OpenVPN Client (flavor, OS):

**Comment by jkroepke** [comment]
Seconds at auth-gen-token defines the maximal lifetime of a VPN session. If reached, the connection needs to be terminated and a full reconnect is manatory. Ref: https://github.com/jkroepke/openvpn-auth-oauth2/wiki/Non-interactive-session-refresh


if auth-token-gen is enabled, `oauth2.refresh.use-session-id` should be set to true.

**Comment by Laboltus** [comment]
Indeed, with oauth2.refresh.use-session-id it terminates the connection and requires interactive auth. Thanks.

**Comment by jkroepke** [comment]
I will try to catch this behavior in code, so I re-open this.
