### ISSUE TITLE
Feature Request: Support Symbolic Links for HTTPS Certificates in OpenVPN-auth-oauth2

### ISSUE THREAD

**Issue by Elshirak** [jkroepke/openvpn-auth-oauth2#335]
### Problem Statement

Hello!

I’m curious whether it’s possible for the OpenVPN-auth-oauth2 HTTPS listener to operate using symbolic links for certificates, or if it’s necessary to place the certificates directly in `/etc/openvpn-auth-oauth2/`. Using symbolic links would make it much easier to maintain and update the certificates. 

In this setup, a user would only need to create a symlink to the default Certbot paths, like this:

```
[root@openvpn openvpn]# ls -la /etc/openvpn-auth-oauth2/
total 20
drwxrwxrwx.  2 root openvpn-auth-oauth2    65 Oct 30 13:16 .
drwxr-xr-x. 81 root root                16384 Oct 30 12:20 ..
-rw-r-----.  1 root openvpn-auth-oauth2   685 Oct 30 12:44 config.yaml
lrwxrwxrwx.  1 root openvpn-auth-oauth2    43 Oct 30 12:41 fullchain.pem -> /etc/letsencrypt/live/openvpn/fullchain.pem
lrwxrwxrwx.  1 root openvpn-auth-oauth2    41 Oct 30 13:16 privkey.pem -> /etc/letsencrypt/live/openvpn/privkey.pem
[root@openvpn openvpn]# ls -la /etc/letsencrypt/live/openvpn/
total 4
drwxr-xr-x. 2 root root  93 Oct 30 11:22 .
drwx------. 3 root root  35 Oct 30 11:07 ..
-rw-r--r--. 1 root root 692 Oct 30 11:07 README
lrwxrwxrwx. 1 root root  31 Oct 30 11:22 cert.pem -> ../../archive/openvpn/cert2.pem
lrwxrwxrwx. 1 root root  32 Oct 30 11:22 chain.pem -> ../../archive/openvpn/chain2.pem
lrwxrwxrwx. 1 root root  36 Oct 30 11:22 fullchain.pem -> ../../archive/openvpn/fullchain2.pem
lrwxrwxrwx. 1 root root  34 Oct 30 11:22 privkey.pem -> ../../archive/openvpn/privkey2.pem
```

Every few months, Certbot renews the certificate, storing it alongside the previous version (with an incremented number in the filename), and updates symbolic links (the “live” reference) to the new certificate.

Would it be possible for the listener to reference certificates via symbolic links, so users wouldn’t need to copy the certificate itself into `/etc/openvpn-auth-oauth2/` each time it updates?

I’ve reviewed the [documentation](https://github.com/jkroepke/openvpn-auth-oauth2/wiki/HTTPS-Listener#using-native-https-support) but noticed an area where we might make an improvement. How do you feel about adding support for this feature?

### openvpn-auth-oauth2 logs

```shell
Oct 30 12:49:37 my.host openvpn-auth-oauth2[42601]: time=2024-10-30T12:49:37.165Z level=ERROR msg="error http listener: tls.LoadX509KeyPair: open /etc/openvpn-auth-oauth2/fullchain.pem: permission denied"
```

### Environment

- openvpn-auth-oauth2 Version: 1.22.2
- OpenVPN Server Version:
- Server OS:
- OpenVPN Client (flavor, OS):

**Comment by Elshirak** [comment]
@jkroepke Thank you for the feedback! 

I'm using RHEL; however, disabling SELinux didn't help. Yes, the target file has openvpn-auth-oauth2 group permissions:

```
[root@openvpn ~]# ls -la /etc/letsencrypt/archive/openvpn/fullchain2.pem 
-rw-r--r--. 1 root openvpn-auth-oauth2 3778 Oct 30 11:22 /etc/letsencrypt/archive/openvpn/fullchain2.pem
```

I think the issue might be related to the dynamic user, possibly affecting file permissions. I resolved it by running the `openvpn-auth-oauth2` systemd service as the root user. In this case, the links work correctly. I modified the `/usr/lib/systemd/system/openvpn-auth-oauth2.service` file as follows:

```
[Service]
# Run as an unprivileged user with random user id.
# DynamicUser=true
# User=openvpn-auth-oauth2-dynamic
# Group=openvpn-auth-oauth2-dynamic
# SupplementaryGroups=openvpn-auth-oauth2

User=root
Group=openvpn-auth-oauth2
```

**Comment by jkroepke** [comment]
It might be a false positive, since the root user is allowed to ignore file permissions.

Could you retry it with `User=nobody`?

**Comment by jkroepke** [comment]
the problem is cleary visible:

```
[root@openvpn openvpn]# ls -la /etc/letsencrypt/live/openvpn/
total 4
drwxr-xr-x. 2 root root  93 Oct 30 11:22 .
drwx------. 3 root root  35 Oct 30 11:07 ..
```

The permissions of the directory `/etc/letsencrypt/live/` is 700. Only root users has permissions to read files inside `/etc/letsencrypt/live/`

**Comment by Elshirak** [comment]
@jkroepke Thank you!
