### ISSUE TITLE
Add apk / alpine packages to releases

### ISSUE THREAD

**Issue by mzhaase** [jkroepke/openvpn-auth-oauth2#351]
### Problem Statement

It would be nice to also have alpine linux packages (apk) available. Alpine linux is widely used in kubernetes/container-based environments. Notably, the most popular openvpn container (>1B pulls) [kylemanna](https://github.com/kylemanna)/[docker-openvpn](https://github.com/kylemanna/docker-openvpn) is using alpine.

### Proposed Solution

Goreleaser supports apk packages: https://goreleaser.com/customization/nfpm/ It seems all that is necessary is to add "apk" to the list of formats.

### Acceptance Criteria

- [ ] As a user, I can also download apk packages in releases.

**Comment by jkroepke** [comment]
What the benefit of do curl | tar xz over apk on a docker bulid?


> Notably, the most popular openvpn container (>1B pulls) [kylemanna](https://github.com/kylemanna)/[docker-openvpn](https://github.com/kylemanna/docker-openvpn) is using alpine.

Which is btw outdated since 4 years and ships a OpenVPN version which is not compatible with `openvpn-auth-oauth2`.

From best-practice and security point of view, openvpn-auth-oauth2 should run in a distinct container rather then inside OpenVPN container.

**Comment by mzhaase** [comment]
> What the benefit of apk over `curl | tar xz ` on a docker bulid?
Well, same reason for deb and rpm: you gain all the advantages of being able to use package managers
- dependency management
- ability to host your own internal repos

**Comment by Quarky9** [comment]
I have an Alpine APK in our company overlay at https://git.zero-downtime.net/ZeroDownTime/alpine-overlay/src/branch/main/kubezero/openvpn-auth-oauth2 which we use to integrate openvpn-auth-oauth2 into our custom OpenVPN container at https://git.zero-downtime.net/ZeroDownTime/zdt-openvpn

**Comment by jkroepke** [comment]
Great! @mzhaase if you are hosting a internal repository, you may already familiar with setup own packages. 

I understand the point with dependencies, but openvpn-auth-oauth2 does have any dependencies. Feel free to use the builds from @Quarky9.

If I would offer an official apk for openvpn-auth-oauth2, people would expect a service file as well. (I would expect that, too).

However, alpine does not support systemd unit files and I'm not going to write shell scripts for services files.

**Comment by mzhaase** [comment]
Understandable.

Thanms for your effort and the great project!
