### ISSUE TITLE
Client problem

### ISSUE THREAD

**Issue by lsx1205** [jkroepke/openvpn-auth-oauth2#360]
### Problem Statement

When we were using openvpn client, there was a situation that the agent agent did not start with the client, so we could not connect to openvpn and had to start it manually, and the official solution was not provided. I would like to ask whether the oauth plug-in can be adapted to other vpn clients，we use other client tools to call the oauth plug-in to authenticate.

### openvpn-auth-oauth2 logs

```shell
*
```

### Environment

- openvpn-auth-oauth2 Version:
- OpenVPN Server Version:
- Server OS:
- OpenVPN Client (flavor, OS):

**Comment by jkroepke** [comment]
openvpn-auth-oauth2 is an server exclusive addon. You can use any client that based on OpenVPN 2.6 on higher.

**Comment by lsx1205** [comment]
Is Tunnelblick OK? It is also based on openvpn

**Comment by lsx1205** [comment]
Thank you, but when I used Tunnelblick4.0.1 to import the ovpn file of openvpn directly, an error occurred, indicating that key or auth/pass must be used, but I can normally invoke the oauth plug-in using the openvpn client. Is there any additional configuration for this?
<img width="678" alt="image" src="https://github.com/user-attachments/assets/b3032394-1680-42a2-8bec-e5ee547953b9">

**Comment by jkroepke** [comment]
See also https://github.com/jkroepke/openvpn-auth-oauth2/wiki/FAQ#q-options-error-no-client-side-authentication-method-is-specified

**Comment by jkroepke** [comment]
Tunnelblick fully depends on OpenVPN2 and OpenVPN2 has the mention issue on all clients
