### ISSUE TITLE
OpenVPN with OIDC - client side configuration?

### ISSUE THREAD

**Issue by Trashmee** [jkroepke/openvpn-auth-oauth2#375]
### Problem Statement

Hi,
your enhancement got me excited - would be great if you could give me some hints to push it through:

Setup:
 - OpenVPN 2.6.12 x86_64 (running - no Mgmt UI in place - wouldn't know what to do there)
 - openvpn-auth-oauth2_1.22.4_linux_amd64 (running & connecting to OpenVPN)
 - OpenVPN GUI 11.27.0 / OpenVPN 2.5.6 client - community editions
 - OIDC clientid + secret + URLs in place
 - nginx https cert redirecting to :9000 (works)
 - index.gohtml template in place
 - Don't worry about the IP ranges in below logs - I changed them for privacy reasons.

Current questions:
 - What would my Client Config look like? I do have a parallel instance with 'standard' certificates in place that I could use as a starter - but what are the differences required here?
 - When going to https://openvpn.company.com I get redirected to :9000 - but there I get "404 page not found". I have index.html (real dump html) + index.gohtml (your template) in place - doesn't seem to matter.
 - When tying to connect via OpenVPN client GUI I just get a username / password prompt (no redirect to https OIDC company auth) - and even if providing username + password there the Client seems to stall w/o something reasonable in the server logs.

Pretty sure I'm missing something conceptionally, would really appreciate the docs mentioning how to proceed after server configuration.

```
2024-12-16 10:49:12 WARNING: Compression for receiving enabled. Compression has been used in the past to break encryption. Sent packets are not compressed unless "allow-compression yes" is also set.
2024-12-16 10:49:12 --cipher is not set. Previous OpenVPN version defaulted to BF-CBC as fallback when cipher negotiation failed in this case. If you need this fallback please add '--data-ciphers-fallback BF-CBC' to your configuration and/or add BF-CBC to --data-ciphers.
2024-12-16 10:49:12 OpenVPN 2.5.6 Windows-MSVC [SSL (OpenSSL)] [LZO] [LZ4] [PKCS11] [AEAD] built on Mar 16 2022
2024-12-16 10:49:12 Windows version 10.0 (Windows 10 or greater) 64bit
2024-12-16 10:49:12 library versions: OpenSSL 1.1.1n  15 Mar 2022, LZO 2.10
2024-12-16 10:49:15 WARNING: normally if you use --mssfix and/or --fragment, you should also set --tun-mtu 1500 (currently it is 1200)
2024-12-16 10:49:15 TCP/UDP: Preserving recently used remote address: [AF_INET]192.168.0.10:1194
2024-12-16 10:49:15 UDP link local: (not bound)
2024-12-16 10:49:15 UDP link remote: [AF_INET]192.168.0.10:1194
2024-12-16 10:49:16 VERIFY OK: depth=1, CN=vpn-gateway
2024-12-16 10:49:16 VERIFY KU OK
2024-12-16 10:49:16 Validating certificate extended key usage
2024-12-16 10:49:16 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
2024-12-16 10:49:16 VERIFY EKU OK
2024-12-16 10:49:16 VERIFY OK: depth=0, CN=vpn-gateway
```

### openvpn-auth-oauth2 logs

```shell
#  journalctl -flu openvpn-auth-oauth2
Dec 16 08:57:15 openvpn openvpn-auth-oauth2[32524]: time=2024-12-16T08:57:15.733+01:00 level=INFO msg="manually configure oauth2 provider with provider generic and providerConfig https://preprod.login.domain.com/oidc/endpoint/default/authorize and https://preprod.login.domain.com/oidc/endpoint/default/token"
Dec 16 08:57:15 openvpn openvpn-auth-oauth2[32524]: time=2024-12-16T08:57:15.734+01:00 level=WARN msg="generic provider with manual configuration is used. Validation of user data is not possible."
Dec 16 08:57:15 openvpn openvpn-auth-oauth2[32524]: time=2024-12-16T08:57:15.735+01:00 level=INFO msg="connect to openvpn management interface unix:///run/openvpn/server.sock"
Dec 16 08:57:15 openvpn openvpn-auth-oauth2[32524]: time=2024-12-16T08:57:15.736+01:00 level=INFO msg="start HTTP server listener on [::]:9000"
Dec 16 08:57:15 openvpn openvpn-auth-oauth2[32524]: time=2024-12-16T08:57:15.737+01:00 level=INFO msg="openvpn-auth-oauth2 started with base url http://192.168.100.226:9000/"
Dec 16 08:57:15 openvpn openvpn-auth-oauth2[32524]: time=2024-12-16T08:57:15.737+01:00 level=DEBUG msg="password probe: ENTER PASSWORD:"
Dec 16 08:57:15 openvpn openvpn-auth-oauth2[32524]: time=2024-12-16T08:57:15.737+01:00 level=DEBUG msg=test
Dec 16 08:57:15 openvpn openvpn-auth-oauth2[32524]: time=2024-12-16T08:57:15.737+01:00 level=INFO msg="connection to OpenVPN management interface established."
Dec 16 08:57:15 openvpn openvpn-auth-oauth2[32524]: time=2024-12-16T08:57:15.737+01:00 level=DEBUG msg=version
Dec 16 08:57:15 openvpn openvpn-auth-oauth2[32524]: time=2024-12-16T08:57:15.737+01:00 level=INFO msg="OpenVPN Version: OpenVPN 2.6.12 x86_64-redhat-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] [DCO] - Management Version: 5"
```

```
tail -f /var/log/openvpn.log
net_iface_up: set tun0 up
net_addr_ptp_v4_add: 10.10.0.1 peer 10.10.0.2 dev tun0
net_route_v4_add: 10.10.0.0/24 via 10.10.0.2 dev [NULL] table 0 metric -1
Could not determine IPv4/IPv6 protocol. Using AF_INET
Socket Buffers: R=[212992->425984] S=[212992->425984]
UDPv4 link local (bound): [AF_INET][undef]:1194
UDPv4 link remote: [AF_UNSPEC]
MULTI: multi_init called, r=256 v=256
IFCONFIG POOL IPv4: base=10.10.0.4 size=62
Initialization Sequence Completed
MANAGEMENT: Client connected from /run/openvpn/server.sock
MANAGEMENT: CMD 'version'
192.168.0.16:51530 Sent fatal SSL alert: unknown
192.168.0.16:51530 OpenSSL: error:0A0000C7:SSL routines::peer did not return a certificate:
192.168.0.16:51530 TLS_ERROR: BIO read tls_read_plaintext error
192.168.0.16:51530 TLS Error: TLS object -> incoming plaintext read error
192.168.0.16:51530 TLS Error: TLS handshake failed
192.168.0.16:51530 SIGUSR1[soft,tls-error] received, client-instance restarting
192.168.0.16:51530 TLS Error: Unroutable control packet received from [AF_INET]192.168.0.16:51530 (si=3 op=P_CONTROL_V1)
192.168.0.16:51530 TLS Error: Unroutable control packet received from [AF_INET]192.168.0.16:51530 (si=3 op=P_CONTROL_V1)
```
```


### Environment

- openvpn-auth-oauth2 Version:
- OpenVPN Server Version:
- Server OS:
- OpenVPN Client (flavor, OS):


### Preflight Checklist

- [X] I could not find a solution in the [documentation](https://github.com/jkroepke/openvpn-auth-oauth2/wiki),
the [FAQ](https://github.com/jkroepke/openvpn-auth-oauth2/wiki/FAQ), the existing issues or discussions.

**Comment by jkroepke** [comment]
I'm bit confused about your style of asking questions.

> When going to [openvpn.company.com](https://openvpn.company.com/) I get redirected to :9000 - but there I get "404 page not found". I have index.html (real dump html) + index.gohtml (your template) in place - doesn't seem to matter.

Yeah, there is no index page. It's not needed. However you can call `/ready` to get an 200 OK.

> When tying to connect via OpenVPN client GUI I just get a username / password prompt

Yeah, you have to add

```
<auth-user-pass>
username
password
</auth-user-pass>
```

to your client config. `auth-user-pass-optional` is mandatory on server as well.

If you still have clients with certificate based authentication, you have to set `verify-client-cert optional` on server. In openvpn-auth-oauth2, you must configure clients CNs at `openvpn.bypass.common-names`. If client, clients with client certificates are redirected to OIDC as well, including machine accounts.

**Comment by Trashmee** [comment]
Hi Jan-Otto,

> I'm bit confused about your style of asking questions.
sorry about that, is that because I opened an "issue" labeled as question or because the way that I phrased what I'm struggeling with? Don't hesitate to tell me how to improve, I value your asset / support.

You're comments look helpful, I hope that I'll be able to test them by Friday & will provide feedback. Don't hesitate to close this "issue" if it concerns you - if there is forum to post this type of question for community support I can also move there.

Kind regards,
Alex

**Comment by Trashmee** [comment]
I had the auth related parameters on client / server side, but your `verify-client-cert optional` was to to the point.

Now I get an error that might indicate I have a client side issue, I'll try an upgrade.

```
192.168.0.221:52269 TLS: Username/Password authentication deferred for username 'user@domain.com'
192.168.0.221:52269 TLS: move_session: dest=TM_ACTIVE src=TM_INITIAL reinit_src=1
192.168.0.221:52269 TLS: tls_multi_process: initial untrusted session promoted to semi-trusted
MANAGEMENT: CMD 'client-deny 1 1 "OpenVPN Client does not support SSO authentication via webauth"'
MULTI: connection rejected: OpenVPN Client does not support SSO authentication via webauth, CLI:[NULL]
```

If that works I'll have to figure how to redirect to an https SSO page instead of polling username / password via the OpenVPN GUI. But maybe that'll happen with the client upgrade already, will see.

**Comment by Trashmee** [comment]
Wow, it just worked after upgrading the OpenVPN GUI / client. 
Please allow one last question - would you know by mind how to avoid the OpenVPN community edition prompting for username / password? 

Even if providing invalid credentials it will redirect to :9000 & use SSO bsaed signon (perfect) - but asking for a username / password within the OpenVPN UI in the first place is something I would avoid for convenience / security reasons.

Pretty cool plugin!

**Comment by jkroepke** [comment]
Hi thanks! 

The workaround for user/password is to define some dummy credentials inside the config.

<auth-user-pass>
username
password
</auth-user-pass>

Limiting groups depends on your OIDC. Please refer the docs first.
