### ISSUE TITLE
 openvpn-auth-oauth2 requires OpenVPN management interface version 5 or higher

### ISSUE THREAD

**Issue by DenVilk** [jkroepke/openvpn-auth-oauth2#48]
### Current Behavior

 openvpn-auth-oauth2 requires OpenVPN management interface version 5 or higher

### Expected Behavior

Working plugin

### Steps To Reproduce

```Markdown
1. configuring openvpn with [script](https://rawsrv.medium.com/how-to-install-your-own-openvpn-server-in-under-five-minutes-6d8624f18a50)
2. setup openvpn-auth-oauth2 as linux package
3. configuring plugin as in wiki
```

### Environment

- openvpn-auth-oauth2 Version: 1.8.0
- OpenVPN Server Version: 2.4.12
- Server OS: Centos stream 8
- OpenVPN Client (flavor, OS): tunnelblick, macos

**Comment by jkroepke** [comment]
> Expected Behavior
> Working plugin

> OpenVPN Server Version: 2.4.12

Please upgrade your OpenVPN server to 2.6.2+ as mention in [README](https://github.com/jkroepke/openvpn-auth-oauth2?tab=readme-ov-file#version-requirements)
