### ISSUE TITLE
IDP Connection

### ISSUE THREAD

**Issue by DenVilk** [jkroepke/openvpn-auth-oauth2#50]
I've tried to use this plugin with Github(doesn't work), goAuthentik(doesn't work), Zitadel(doesn't work).
Can you write some instructions how to setup library with any of this IDP, please?

**Comment by jkroepke** [comment]
With #52 Github should work for know.

Here is a working configuration for AzureAD (IDP):

```
CONFIG_HTTP_BASEURL=https://server.example.com
CONFIG_HTTP_CERT=server.example.com.crt
CONFIG_HTTP_KEY=server.example.com.key
CONFIG_HTTP_SECRET=Oovai7lei5eemee4
CONFIG_HTTP_TLS=true
CONFIG_LOG_LEVEL=info
CONFIG_OAUTH2_CLIENT_ID=ID
CONFIG_OAUTH2_CLIENT_SECRET=secret
CONFIG_OAUTH2_ISSUER=https://login.microsoftonline.com/$TENANTID/v2.0
CONFIG_OPENVPN_ADDR=tcp://127.0.0.1:808
CONFIG_OPENVPN_PASSWORD=password
```

**Comment by DenVilk** [comment]
How can I build your project? And as I saw in your code, there is some using of smth from zitadel, did you test work with it? Maybe there is configuration for it?

**Comment by DenVilk** [comment]
@jkroepke or may be you can release new version?

**Comment by jkroepke** [comment]
Run `make build` on root dir

yeah, I'll do

**Comment by jkroepke** [comment]
Check: https://github.com/jkroepke/openvpn-auth-oauth2/releases/tag/v1.10.0

**Comment by DenVilk** [comment]
> Check: https://github.com/jkroepke/openvpn-auth-oauth2/releases/tag/v1.10.0

I have some issues with building package, because of go version trouble 
```invalid go version '1.21.1': must match format 1.23```

**Comment by jkroepke** [comment]
See like to local `go version` is older than go 1.21. Anyways, I remove the patch version

**Comment by DenVilk** [comment]
Thank you for help <3
Perhaps in the near future I will help with documentation and examples

**Comment by DenVilk** [comment]
Is there opportunity to turn off auth window from vpn client, leave only authorization via the browser?

**Comment by jkroepke** [comment]
The auth flow is per connection and always initated by the VPN server client.
