### ISSUE TITLE
Install & Configure Plugin On OpenVPN Access Server (OpenVPN-AS)

### ISSUE THREAD

**Issue by VietDuc19** [jkroepke/openvpn-auth-oauth2#60]
### Problem Statement

Hi Team.
The latest version of OpenVPN Access Server now supports client authentication with Azure AD using the SAML protocol. However, for personal reasons, my OpenVPN Access Server is still using an older version that does not support client authentication with Azure AD. Therefore, I am currently looking for a way to authenticate OpenVPN-AS clients with Azure AD.
After reading:
https://github.com/jkroepke/openvpn-auth-oauth2/wiki
https://medium.com/@jkroepke/openvpn-sso-via-oauth2-ab2583ee8477
I installed plugin successfully on my OpenVPN-AS server, configured configuration file and try to start openvpn-auth-oauth2 service but got the following error:
Failed to add match 'openvpn-auth-oauth2': Invalid argument
I wonder if the plugin works with OpenVPN Access Server or not. And if it does, has anyone successfully set it up and configured it?
Please provide me with the documentation or instructions for this configuration if possible.
I sincerely appreciate your help.

### Additional information

- OpenVPN Access Server Version 2.5
- Ubuntu Server 16.04 LTS

**Comment by jkroepke** [comment]
The error

> Failed to add match 'openvpn-auth-oauth2': Invalid argument

seems more systemd related. Because I find some issues around `Failed to add match 'xxx': Invalid argument`

Can you run openvpn-auth-oauth2 from a shell, without using systemd?

---

In general, AS server is untested and I'm not sure if the authentication from openvpn-auth-oauth2 conflicts with AS server one. I also have no idea, if OVPN management interface is availible on AS.

**Comment by VietDuc19** [comment]
Hi @jkroepke
Thank you so much for your quick response. After running:
# /usr/bin/openvpn-auth-oauth2
I got the following error:
error loading config: validation error: http.secret is required
But in configuration file /etc/sysconfig/openvpn-auth-oauth2, I defined variable CONFIG_HTTP_SECRET.
If you haven't already checked on the AS server, could you plan to investigate and develop a plugin for the AS server? I really need this plugin for the AS server.

**Comment by jkroepke** [comment]
The connection between  /etc/sysconfig/openvpn-auth-oauth2 and /usr/bin/openvpn-auth-oauth2 is done by systemd. The file is ignored, if systemd is not used for the start.

For now, you have to pass the config manually with the env command

```bash
env CONFIG_HTTP_SECRET=abc CONFIG_XXX=YYY CONFIG_XXX=YYY CONFIG_XXX=YYY CONFIG_XXX=YYY /usr/bin/openvpn-auth-oauth2
```

**Comment by VietDuc19** [comment]
It seems like I have successfully executed it:
/usr/bin/openvpn-auth-oauth2 
msg="discover oidc auto configuration with provider generic for issuer https://login.microsoftonline.com/AZURE-TENANT-ID/oauth2/v2.0/authorize"
msg="newProviderWithDiscovery: http status not ok: 404 Not Found "
 I will need to double-check the value of CONFIG_OAUTH2_ISSUER.
Furthermore, I don't know how to connect openvpn-auth-oauth2 with openvpn-as server. I added the following lines into configuration file of AS server (/usr/local/openvpn_as/etc/as.conf):
management AS_MANAGEMENT_IP AS_MANAGEMENT_PORT /usr/local/openvpn_as/etc/password.txt
management-hold
management-client-auth
Is this correct? I really can't find any documentation on how to add configuration to this as.conf file from OpenVPN Access Server documentation.

**Comment by jkroepke** [comment]
> I really can't find any documentation on how to add configuration to this as.conf

Correct. AS was nether tested. And I don't have any experience in AS. Sorry. 

```
management AS_MANAGEMENT_IP AS_MANAGEMENT_PORT /usr/local/openvpn_as/etc/password.txt
management-hold
management-client-auth
```

Is correct for an OpenVPN server config file, but I have no idea how to configure it on AS.

**Comment by VietDuc19** [comment]
Thank you so much for your help @jkroepke 
Hope you will release a new version that can support OpenVPN Access Server.
Wish you have a good day.

**Comment by jkroepke** [comment]
>  that can support OpenVPN Access Server.

Since the Access Server already provides SSO capabilities, future support for AS is not planned. Sorry.
