### ISSUE TITLE
Is there opportunity to use CCD with user groups?

### ISSUE THREAD

**Issue by DenVilk** [jkroepke/openvpn-auth-oauth2#63]
### Problem Statement

I have Zitadel or anyone other SSO with configured user groups. I want to split resources in my vpn network by access for groups of users. In most cases .ccd used for it. How can we do it with that plugin?

### Proposed Solution

Add splitted configurations for groups with routes to resources

**Comment by jkroepke** [comment]
I can develop such an feature, I may need some help for design a admin friendly interface
What about 2 new flags

```
--client-config-dir <ccd-dir>
--client-config-claim roles
````

In case that the claim contains a list of string, multiple files will be loaded can concatenate

**Comment by DenVilk** [comment]
Sounds good, but what will the flag ```--client-config-claim roles``` do?

**Comment by DenVilk** [comment]
And there is a moment, I'm not sure if this is possible at all, since usually the client's ip is specified in the ccd configurations.

**Comment by jkroepke** [comment]
--client-config-claim roles

openvpn-auth-oauth2 will ask the IDP about an ID Token (OIDC authorization code flow) and the ID Token has multiple claims (fields) based on the requested scope. For example if a groups [scope](https://zitadel.com/docs/apis/openidoauth/scopes) is requested, then the ID Token may have an [claim](https://zitadel.com/docs/apis/openidoauth/claims) called groups which contains all groups.

**Comment by DenVilk** [comment]
Okey, I understood now. But can you check what I said before about client's IP, because I think it can be bottle neck in this task

**Comment by jkroepke** [comment]
but client IP is an user level setting, but an group based setting or am I wrong?

**Comment by DenVilk** [comment]
We need to set subnet for group, not specific IP like in ccd config. I'm talking about that.

**Comment by jkroepke** [comment]
At least this feature does not exists in OpenVPN yet

References:
* https://community.openvpn.net/openvpn/ticket/1173
* https://community.openvpn.net/openvpn/ticket/1419

**Comment by DenVilk** [comment]
![dog-burning](https://github.com/jkroepke/openvpn-auth-oauth2/assets/30044072/baf6093d-4eea-4386-b667-310323a0bdd9)

**Comment by jkroepke** [comment]
@DenVilk IPAM for clients is not in scope, I feel that could be a bit error prune at the moment. openvpn-auth-oauth2 has no state and can't save client IPs.
