### ISSUE TITLE
Google as a Provider

### ISSUE THREAD

**Issue by vincib** [jkroepke/openvpn-auth-oauth2#81]
### Problem Statement

I'd like to use google workspaces as a oauth2 provider with this program

### Proposed Solution

I found a way to configure it and it worked, I'll post here the configuration I used, if you want to enhance your documentation :)

**Comment by jkroepke** [comment]
If you want, you can contribute docs here:

* https://github.com/jkroepke/openvpn-auth-oauth2/blob/main/docs/Providers.md

What it would REALLY helpful is what is todo on Google site, e.g. setup whatever.

> #CONFIG_OAUTH2_PROVIDER=google

Good to see, that a dedicated provider is not needed.

**Comment by vincib** [comment]
to create the app in your google workspace : 

- from here https://console.cloud.google.com/
- click on Create a new project or select an existing project
- then API & Services, then Credentials
- click "create credentials"  of type "OAuth Client ID"
- set a name for your app
- in the Authorized Redirect URIs add one and set it to https://yourdomain/oauth2/callback
- you'll get your client id and client secret 
- use those in the config as shown above

**Comment by vincib** [comment]
I'll do a pull request on your doc
