### ISSUE TITLE
How to use openvpn to connect to casdoor And use Wecom as Casdoor's provider?

### ISSUE THREAD

**Issue by FanKang2021** [jkroepke/openvpn-auth-oauth2#87]

**Comment by jkroepke** [comment]
I have no idea

**Comment by FanKang2021** [comment]
> I have no idea, but casdoor supports OIDC https://casdoor.org/de/docs/how-to-connect/oidc-client which is compatible to openvpn-auth-oauth2 out of the box

Yes,it's  compatible to openvpn-auth-oauth2 out of the box.However, after configuring the openvpn server, I use the client connection to jump to the callback casdoor on the web page, and the message returned to me is failed to exchange token: oidc: json: cannot unmarshal array into Go struct field itcAlias.address of type oidc.UserInfoAddress into *oidc.itcAlias”.

**Comment by FanKang2021** [comment]
@jkroepke Could you help me test this problem?

**Comment by jkroepke** [comment]
Whats your configuration?

**Comment by FanKang2021** [comment]
It's my configuration.

**Comment by jkroepke** [comment]
could you try this:

* CONFIG_OAUTH2_SCOPES=openid

**Comment by FanKang2021** [comment]
what's the openid?

**Comment by jkroepke** [comment]
Thats the root cause:

* https://github.com/casbin/casdoor/issues/1184

Casdoor is using an address field inside the token which is not standard conform and the error 

>  json: cannot unmarshal array into Go struct field itcAlias.address of type oidc.UserInfoAddress into *oidc.itcAlias”.

Says that the format of the field can not be translated into the expected structure.

Be reducing the scopes, the hope is that the field is omit from token which should avoid the error maybe.

**Comment by jkroepke** [comment]
#88 could be a potential fix here, because I used a minimal token interface which ignore the address token field. I do not use the field anyways, It's safe to ignore.

**Comment by jkroepke** [comment]
https://github.com/jkroepke/openvpn-auth-oauth2/actions/runs/7259045867?pr=88 at the bottom, there is a Artifact named dist which contains the linux binary that contains the fix. 

It's possible that you test this?

**Comment by FanKang2021** [comment]
When I use min-tonken to compile and install, I report an ERROR "time=2023-12-19T09:28:54.421Z level=ERROR msg="error loading config: validation error: oauth2.client.id is required""
