### ISSUE TITLE
Ami Support

### ISSUE THREAD

**Issue by temp1234567878** [jkroepke/openvpn-auth-oauth2#90]
### Problem Statement

Does this code support the OpenVPN Access Server AMI version?

 openvpn-auth-oauth2 --http.secret=xxxxxx--oauth2.client.id=xxxxxxxxx --oauth2.client.secret=xxxxxxxx --oauth2.issuer=https://accounts.google.com --http.baseurl=https://xxxxxx:9000/ --http.listen=:9000
 
 As far as i understand the port (9000) selected will be new.
 
time=2023-12-20T23:38:30.936Z level=INFO msg="discover oidc auto configuration with provider generic for issuer https://accounts.google.com"
time=2023-12-20T23:38:30.967Z level=INFO msg="start HTTP server listener on :9000 with base url https://xxxxxxxxxx:9000/"
time=2023-12-20T23:38:30.967Z level=INFO msg="connect to openvpn management interface unix:/run/openvpn/server.sock"
time=2023-12-20T23:38:30.967Z level=ERROR msg="error OpenVPN: unable to connect to openvpn management interface unix:/run/openvpn/server.sock: dial unix /run/openvpn/server.sock: connect: no such file or directory"
time=2023-12-20T23:38:30.968Z level=INFO msg="shutdown OpenVPN management connection"
time=2023-12-20T23:38:30.968Z level=INFO msg="start graceful shutdown of http listener"
time=2023-12-20T23:38:30.968Z level=INFO msg="http listener successfully terminated"

Ami version does not have :/run/openvpn/server.sock running on ubuntu.
But have this
#/usr/local/openvpn_as/etc/sock# ls
sagent  sagent.api  sagent.localroot

Thanks in advance.

### Additional information

Could be easier if we have a google section.

**Comment by jkroepke** [comment]
Hi,

this plugin does not work with any `OpenVPN Access Server`. It' only works with the standalone OpenVPN Server.

I as know, OpenVPN Access Server has already SSO integrated.

**Comment by temp1234567878** [comment]
> Hi,
> 
> this plugin does not work with any `OpenVPN Access Server`. It' only works with the standalone OpenVPN Server.
> 
> I as know, OpenVPN Access Server has already SSO integrated.

What do you mean with "standalone OpenVPNServer" ?
assume that you refer
https://openvpn.net/community-downloads/
Because there is the only one.
